### ISSUE TITLE
질문이요

### ISSUE THREAD

**Issue by dragondy** [noonmaru/psychics#10]
어떻게 적용하죠?

**Comment by pllume** [comment]
1. psychics-0.6.0.zip 을 다운받고 그 안에 있는 psychics-0.6.0 파일을 꺼집어내줍니다
2. 명령 프롬포트를 실행하신 후 cd (psychics-0.6.0 파일 경로) 를 쳐줍니다
3. 그리고 gradlew.bat tasks 을 칩니다
4. 그리고 거기 tasks 중에서 ShadowJar를 선택합니다
5. psychics-0.6.0\psychics-common\build\libs 안에 Psychics.jar가 생성되었을 겁니다

자 이제 이 플러그인을 적용시키기 위해서는 다음 플러그인이 필요합니다.
1. AutoReloader 1.0.1
2. InvFX 1.3.0
3. Tap 3.1.7
4. Kotlin-plugin 1.4.10
모두 각별님의 Repositories 안에 있으니 잘 찾아보세요

모두 다운 받으셨다면 Psychics.jar 와 같이 다 plugins 폴더에 넣어주세요

**Comment by sgkill6** [comment]
> Task :tasks

------------------------------------------------------------
Tasks runnable from root project
------------------------------------------------------------

Build Setup tasks
-----------------
init - Initializes a new Gradle build.
wrapper - Generates Gradle wrapper files.

Help tasks
----------
buildEnvironment - Displays all buildscript dependencies declared in root project 'sgkil'.
components - Displays the components produced by root project 'sgkil'. [incubating]
dependencies - Displays all dependencies declared in root project 'sgkil'.
dependencyInsight - Displays the insight into a specific dependency in root project 'sgkil'.
dependentComponents - Displays the dependent components of components in root project 'sgkil'. [incubating]
help - Displays a help message.
model - Displays the configuration model of root project 'sgkil'. [incubating]
outgoingVariants - Displays the outgoing variants of root project 'sgkil'.
projects - Displays the sub-projects of root project 'sgkil'.
properties - Displays the properties of root project 'sgkil'.
tasks - Displays the tasks runnable from root project 'sgkil'.

To see all tasks and more detail, run gradlew tasks --all

To see more detail about a task, run gradlew help --task <task>

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.6/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed

**Comment by sgkill6** [comment]
조금더 정확하게 알려주실 수 있나요?

**Comment by dragondy** [comment]
repositories 폴더가 어디에 있는지 알려주실 수 있나요?

**Comment by dragondy** [comment]
> 조금더 정확하게 알려주실 수 있나요?
그리고 gradlew.bat tasks 을 칩니다
그리고 거기 tasks 중에서 ShadowJar를 선택합니다
혹시 이 부분이 이해가 안되시는 거라면

**Comment by dragondy** [comment]
오류 나와요
gradlew.bat tasks shadowJar 아닌가요?

**Comment by justgameworld** [comment]
1.psychics-0.6.0.zip 을 다운받습니다
2. 원도우 + r 을 눌러 창1개을 열어줌니다
3.창에 cmd 라고 입력후 엔터을 쳐줌니다
4.cd C:\Users\wmwm\Downloads\psychics-0.6.0\psychics-0.6.0 이런식으로 경로을 입력해줍니다 (경로는psychics-0.6.0 파일 안에서 위쪽 내pc > 다운로드 > psychics-0.6.0 > psychics-0.6.0 이런 식으로 있는걸 클릭에 컨트롤 + C 눌러 주소을 복사하고 컨트롤 + v 로 붙여넣기해주시면 됨니다
4.그럼 이재 창에 gradlew.bat tasks 을 쳐주시면 초록색 주황색 하양색이 나와서 복잡해지는데 신경쓰지 마시고 
gradlew.bat tasks  ShadowJar 을 쳐주시면 뒴니다 그럼 다운로드가 시작 되는데 다운로드가 끝나면 psychics-0.6.0 파일 안애 psychics-common 폴더로 들어가 주시고 psychics-common폴더안에 build으로 들어가고 마지막으로 build폴더안에libs으로 들어가 주시면 Psychics.jar 파일이 있을겁니다 누구는 Psychics 이라고도 나옴니다 그걸 자신의 서버 plugins 안에 넣어주시면 능력자 플러그인은 적용이 안됨니다 추가로 플러그인 4개을 넣어주셔야 하는데 psychics-0.6.0 폴더안을 찾는거 보다 재가 플러그인 폴더 주소을 좀 이따 알려드리겠습니다

**Comment by dragondy** [comment]
ㅎㄷㄷ 감사합니다

**Comment by dragondy** [comment]
Rules
-----
Pattern: clean<TaskName>: Cleans the output files of a task.
Pattern: build<ConfigurationName>: Assembles the artifacts of a configuration.
Pattern: upload<ConfigurationName>: Assembles and uploads the artifacts belonging to a configuration.

To see all tasks and more detail, run gradlew tasks --all

To see more detail about a task, run gradlew help --task <task>

> Task :psychics-common:compileKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':psychics-common:compileKotlin'.
> Kotlin could not find the required JDK tools in the Java installation 'C:\Program Files (x86)\Java\jre1.8.0_261' used by Gradle. Make sure Gradle is running on a JDK, not JRE.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
4 actionable tasks: 4 executed

**Comment by dragondy** [comment]
라고 뜹니다.
gradlew.bat tasks를 친 후에
gradlew.bat tasks ShadowJar를 쳤습니다.

**Comment by justgameworld** [comment]
> Task :tasks

------------------------------------------------------------
Tasks runnable from root project
------------------------------------------------------------

Build tasks
-----------
assemble - Assembles the outputs of this project.
build - Assembles and tests this project.
buildDependents - Assembles and tests this project and all projects that depend on it.
buildNeeded - Assembles and tests this project and all projects it depends on.
classes - Assembles main classes.
clean - Deletes the build directory.
jar - Assembles a jar archive containing the main classes.
testClasses - Assembles test classes.

Build Setup tasks
-----------------
init - Initializes a new Gradle build.
wrapper - Generates Gradle wrapper files.

Documentation tasks
-------------------
javadoc - Generates Javadoc API documentation for the main source code.

Help tasks
----------
buildEnvironment - Displays all buildscript dependencies declared in root project 'psychics'.
components - Displays the components produced by root project 'psychics'. [incubating]
dependencies - Displays all dependencies declared in root project 'psychics'.
dependencyInsight - Displays the insight into a specific dependency in root project 'psychics'.
dependentComponents - Displays the dependent components of components in root project 'psychics'. [incubating]
help - Displays a help message.
kotlinDslAccessorsReport - Prints the Kotlin code for accessing the currently available project extensions and conventions.
model - Displays the configuration model of root project 'psychics'. [incubating]
outgoingVariants - Displays the outgoing variants of root project 'psychics'.
projects - Displays the sub-projects of root project 'psychics'.
properties - Displays the properties of root project 'psychics'.
tasks - Displays the tasks runnable from root project 'psychics' (some of the displayed tasks may belong to subprojects).

Publishing tasks
----------------
generateMetadataFileForPsychicsPublication - Generates the Gradle metadata file for publication 'Psychics'.
generatePomFileForPsychicsPublication - Generates the Maven POM file for publication 'Psychics'.
publish - Publishes all publications produced by this project.
publishPsychicsPublicationToMavenLocal - Publishes Maven publication 'Psychics' to the local Maven repository.
publishToMavenLocal - Publishes all Maven publications produced by this project to the local Maven cache.

Shadow tasks
------------
knows - Do you know who knows?
shadowJar - Create a combined JAR of project and runtime dependencies

Verification tasks
------------------
check - Runs all checks.
test - Runs the unit tests.

Rules
-----
Pattern: clean<TaskName>: Cleans the output files of a task.
Pattern: build<ConfigurationName>: Assembles the artifacts of a configuration.
Pattern: upload<ConfigurationName>: Assembles and uploads the artifacts belonging to a configuration.

To see all tasks and more detail, run gradlew tasks --all

To see more detail about a task, run gradlew help --task <task>

BUILD SUCCESSFUL in 898ms
1 actionable task: 1 executed

**Comment by justgameworld** [comment]
이렇께 떠야 정상..인데..

**Comment by justgameworld** [comment]
뭔가 오류가 있었나 봅니다?

**Comment by justgameworld** [comment]
아!

**Comment by dragondy** [comment]
한 28%까지 올라가다가 멈춥니다

**Comment by dragondy** [comment]
classes라는 파일만 존재합니다

**Comment by justgameworld** [comment]
재가 실수 했습니다 가장먼저 psychics-0.6.0안에있는 gradlew.bat파일먼저 열어보시겠어요?

**Comment by dragondy** [comment]
넵

**Comment by dragondy** [comment]
했습니다

**Comment by justgameworld** [comment]
그다음에 2번부터 다시 진행 부탁드리겠습니다

**Comment by dragondy** [comment]
넵

**Comment by dragondy** [comment]
진짜 죄송한데

**Comment by dragondy** [comment]
Pattern: clean<TaskName>: Cleans the output files of a task.
Pattern: build<ConfigurationName>: Assembles the artifacts of a configuration.
Pattern: upload<ConfigurationName>: Assembles and uploads the artifacts belonging to a configuration.

To see all tasks and more detail, run gradlew tasks --all

To see more detail about a task, run gradlew help --task <task>

> Task :psychics-common:compileKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':psychics-common:compileKotlin'.
> Kotlin could not find the required JDK tools in the Java installation 'C:\Program Files (x86)\Java\jre1.8.0_261' used by Gradle. Make sure Gradle is running on a JDK, not JRE.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s
4 actionable tasks: 4 executed

**Comment by dragondy** [comment]
.....
다시 해 보겠습니다.

**Comment by justgameworld** [comment]
Rules
-----
Pattern: clean<TaskName>: Cleans the output files of a task.
Pattern: build<ConfigurationName>: Assembles the artifacts of a configuration.
Pattern: upload<ConfigurationName>: Assembles and uploads the artifacts belonging to a configuration.

To see all tasks and more detail, run gradlew tasks --all

To see more detail about a task, run gradlew help --task <task>

BUILD SUCCESSFUL in 898ms
1 actionable task: 1 executed

**Comment by justgameworld** [comment]
영상으로 재작해야 겠수..

**Comment by justgameworld** [comment]
채팅으로 하면 좀 힘든거 같습니다..

**Comment by dragondy** [comment]
혹시 한번씩 치는거 맞죠?

**Comment by justgameworld** [comment]
1번씩요? 뭘,,?

**Comment by dragondy** [comment]
gradlew.bat tasks를 친 후에
gradlew.bat tasks ShadowJar를 치는거요

**Comment by dragondy** [comment]
psychics-common:compileKotlin 에 문제가 있다는데요....
제가 코딩을 잘하는게 아니라서.....

**Comment by dragondy** [comment]
역시 꼼수는 안통하네요....
psychics-common:compileKotlin 이라고 해서 Kotlin 지웠습니다.

**Comment by dragondy** [comment]
그랬더니 psychics-common:compileKotlin를 못했다고 날리네요

**Comment by dragondy** [comment]
어??

**Comment by dragondy** [comment]
어....... 오류는 났는데 나오긴 했어요

**Comment by dragondy** [comment]
Pattern: clean<TaskName>: Cleans the output files of a task.
Pattern: build<ConfigurationName>: Assembles the artifacts of a configuration.
Pattern: upload<ConfigurationName>: Assembles and uploads the artifacts belonging to a configuration.

To see all tasks and more detail, run gradlew tasks --all

To see more detail about a task, run gradlew help --task <task>

> Task :psychics-abilities:boomerang:compileKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':psychics-abilities:boomerang:compileKotlin'.
> Kotlin could not find the required JDK tools in the Java installation 'C:\Program Files (x86)\Java\jre1.8.0_261' used by Gradle. Make sure Gradle is running on a JDK, not JRE.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s
9 actionable tasks: 9 executed

**Comment by dragondy** [comment]
라고 나오기는 하는데 전에 했었을때 오류났다고 했던 그 폴더를 지우니깐 .jar 파일이 나오기는 합니다.

**Comment by justgameworld** [comment]
아... 파일나 왔어요?

**Comment by dragondy** [comment]
혹시 되는지 테스트 중입니다.

**Comment by dragondy** [comment]
아 안되네요

**Comment by dragondy** [comment]
Plugins (2): LuckPerms, WorldEdit

**Comment by dragondy** [comment]
혹시 스피곳 서버에서는 안되나요?

**Comment by justgameworld** [comment]
아마 페이퍼을 각별님이 이야기 한걸로 봐 페이퍼 전용아닐까요?

**Comment by dragondy** [comment]
....>.... Plugins (2): LuckPerms, WorldEdit

**Comment by dragondy** [comment]
페이퍼도 똑같이 나옵니다.......

**Comment by justgameworld** [comment]
그럼 아마 타 플러그인을 안넣어서 그런게 아닐까요?

**Comment by dragondy** [comment]
혹시 타 플러그인 다운로드 주소를 아시나요?

**Comment by justgameworld** [comment]
일단 폴더안애서 찾아봤는데 아애 없고

**Comment by dragondy** [comment]
혹시 들어가있는 폴더의 이름이 무엇인가요?

**Comment by dragondy** [comment]
아 없습니다.

**Comment by justgameworld** [comment]
psychics-0.6.0 폴더입니다

**Comment by justgameworld** [comment]
AutoReloader 1.0.1
InvFX 1.3.0
Tap 3.1.7
Kotlin-plugin 1.4.10

**Comment by dragondy** [comment]
Repositories 아는가요?

**Comment by justgameworld** [comment]
가 필요한데..

**Comment by justgameworld** [comment]
Repositories = 저장소..

**Comment by dragondy** [comment]
리소스팩의 이름을 쳐도 안나와요......

**Comment by justgameworld** [comment]
https://github.com/noonmaru

**Comment by justgameworld** [comment]
4다 있습니다

**Comment by justgameworld** [comment]
정확히는 다는 아니고 파크루 매이커 까지 있냉

**Comment by dragondy** [comment]
네 잠깐만요

**Comment by justgameworld** [comment]
https://github.com/noonmaru?tab=repositories

**Comment by justgameworld** [comment]
여기에서 찾으시면 될거같아요!

**Comment by dragondy** [comment]
같은 방법으로 다른 플러그인도 다운로드 받으면 되는거죠?

**Comment by dragondy** [comment]
안되는거 같네요.....

**Comment by dragondy** [comment]
나중에 영상이 나온다면 그걸 보고 할게요...

**Comment by justgameworld** [comment]
넴

**Comment by qogusdn1017** [comment]
jdk를 안깔아서 오류난거같네요.
JDK를 깔고 JAVA_HOME 설정하신뒤
gradlew clean shadowJar하시면 됩니다.

**Comment by dragondy** [comment]
를 어떻게 하죠?
인터넷에서 찾아서 하려고 하는데 나오지를 않네요ㅠㅠㅠㅠ

**Comment by dragondy** [comment]
다운로드도 하고 하긴 했는데 어떻게 적용하고, 환경변수 같은거를 모르겠어요.....

**Comment by dragondy** [comment]
유튭에 찾아서 했는데요
안되네요

**Comment by qogusdn1017** [comment]
JDK 8 사용을 권장합니다. JAVA_HOME은 검색하시면 설정법 대부분 나와있습니다.

**그냥 안된다**고 하지 마세요.

**Comment by qogusdn1017** [comment]
Kotlin could not find the required JDK tools in the Java installation 'C:\Program Files (x86)\Java\jre1.8.0_261' used by Gradle. Make sure Gradle is running on a JDK, not JRE.

Kotlin이 자바 설치파일(C:\Program Files(x86)\Java\jre1.8.0_261)에서 Gradle이 사용하는 필요한 JDK 도구를 찾을 수 없습니다. Gradle이 jre이 아닌 jdk에서 작동되는지 확인해주세요.

(해석이 정확히 맞는지는 모르나 확실한건 현재 경로를 보시면 jre로 빌드하려고합니다. JDK를 설치하신뒤 JAVA_HOME 설정하시고 해당 디렉터리에서 gradlew clean shadowJar를 사용해 다시 시도해보세요.)

**Comment by OverseerK** [comment]
JDK JRE 둘중에 하나 설치하신 다음에 윗분 말처럼 환경변수 설정을 먼저 하셔야합니다...

**Comment by qogusdn1017** [comment]
> JDK JRE 둘중에 하나 설치하신 다음에 윗분 말처럼 환경변수 설정을 먼저 하셔야합니다...

오류내용에서 JRE가 아닌 JDK를 요구하고 있습니다. 참고해주세유

**Comment by dragondy** [comment]
> JDK 8 사용을 권장합니다. JAVA_HOME은 검색하시면 설정법 대부분 나와있습니다.
> 
> **그냥 안된다**고 하지 마세요.
3시간동안 해도 안되는것을 어떻게 되는것이라고 할 수 있나요?

**Comment by dragondy** [comment]
실제로 java가 들어가 있는 폴더는 C:\Program Files (x86) 하지만 이 프로그램이 원하는 곳은 C:\
java를 C:\Program Files (x86)에 넣으면 적용X 또한 검색해서 받은 파일은 .gz 압축을 풀면 파일이 나옴
이 파일을 어떻게 적용?
또 어디에 적용? 환경변수는 C:\Program Files (x86)에 적용해야 하나? C:\에 적용해야 하나?
파일을 덮어써야 하나? 아니면 겹치는 것만 덮어써야 하나?
C:\에 있는 java를 지우면 오류, C:\Program Files (x86)에 자바를 지워도 오류
다운로드 받은 파일은 안에 넣어야 하나? 밖에 넣어야 하나?
등등을 대략 2시간동안 하다가 안됐습니다. 어떻게 하죠?

**Comment by dragondy** [comment]
아 참고로 지금 상황이 더 나빠진 것 같습니다.
원래 gradlew.bat tasks 은 됐었는데요
이제는 이것 마저도 오류나요....
gradlew.bat tasks shadowJar는 당연히 오류나고요.......

**Comment by dragondy** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
org/jetbrains/kotlin/cli/common/PropertiesKt
> org.jetbrains.kotlin.cli.common.PropertiesKt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 25s

**Comment by Apple6050** [comment]
@dragondy 정 안돼시면 TeamViewer으로 원격지원 해드리겠습니다

**Comment by Apple6050** [comment]
디스코드 Apple6050#1781으로 연락주세요 @dragondy

**Comment by dragondy** [comment]
되는 것 같네요
근데 28%에서 2분간 멈춰있어요...
컴퓨터를 바꿔야 할듯

**Comment by dragondy** [comment]
오 되네요 닫겠습니다.

**Comment by dragondy** [comment]
답변해주신 모든분들 특히 Apple6050 감사합니다.
