### ISSUE TITLE
적용법 더 자세하게 알려주세요

### ISSUE THREAD

**Issue by sgkill6** [noonmaru/psychics#11]
적용법 더 자세하게 알려주세요

**Comment by Tilto0822** [comment]
#9 에 자세하게 설명되어 있습니다.
위의 글에 적혀있는대로 따라만 해도 기본적인 실행은 모두 할 수 있습니다.
저 설명을 읽고도 모르시겠다면, 직접 이것저것 다 눌러보면서 찾아보세요.
그 정도 노력은 하셔야 원하는 결과물을 얻을 수 있는겁니다.

**Comment by pllume** [comment]
사실 저도 플러그인은 다루지 않아서 잘은 모릅니다;;

정 원하면 디스코드 같은거로 알려드릴게요

그리고 플러그인 적용법은 알려드릴 순 있는데 초능력 적용법은 저도 못 찾았습니다;;

그래서 아직은 API 플러그인만 적용이 되네요

**Comment by sgkill6** [comment]
tasks를 선택하라는게 무슨 뜻인지 모르겠습니다 계속 물어봐서 죄송합니다만

**Comment by sgkill6** [comment]
@pllume 디스코드로 알려주실 수 있나요?

**Comment by jedeop** [comment]
만약 Docker를 사용하신다면 이 Repo Root 디렉토리에서
```sh
docker-compose up -d
./gradlew copyJarToDocker
```
를 실행하면 개발용 마인크래프트 서버 생성 + 플러그인 빌드 후 서버에 추가됩니다.

Docker를 사용하지 않으신다면 #9 처럼 빌드하시고 직접 서버를 구성하시면 됩니다.
추가로 `(RepoRoot)/psychics-abilities`에 각 `능력(Abilities)` 소스가 있으며, #9 를 실행하면 이것도 빌드되어 있을 겁니다. 이 jar 파일을 `(serverRoot)/plugins/Psychics/abilities`에 넣고 서버를 재시작하면 능력이 로드됩니다.

다음으로 `Psychics`를 만들어야 합니다.
`(serverRoot)/plugins/Psychics/psychics` 아래에 `.yml` 형식으로 저장되며, 내용은 [이곳](https://github.com/noonmaru/psychics/blob/master/psychics-common/src/main/kotlin/com/github/noonmaru/psychics/PsychicConcept.kt)을 참고하면 될 듯 합니다.

이후 인게임에서
`/psychics attach (username) (PsychicsName)`
`/psychics attach (PsychicsName)`
을 차례대로 실행하면 Psychics 정보를 확인 할 수 있습니다.

**Comment by Apple6050** [comment]
Issue 닫아주세요...

**Comment by yoomath2018** [comment]
공식 Docs 올렸으니 닫아야 할 듯 합니다
