### ISSUE TITLE
플러그인 관련 질문

### ISSUE THREAD

**Issue by condblock** [noonmaru/psychics#12]
차피 저를 포함한 대부분의 사람들은 이거 빌드 절대 못하잖아요
빌드 성공하신분이 구글드라이브 링크걸어서 주시면 안되나요
아님 별님이 .jar 파일을 주시거나...

**Comment by qasde741** [comment]
ㅇㅈㅇㅈ

**Comment by Apple6050** [comment]
빌드 가능한데요 @qasde741 @condblock

**Comment by Apple6050** [comment]
적용도 되는데 @qasde741 @condblock

**Comment by Apple6050** [comment]
그냥 plugins.zip 업로드하죠 뭐

**Comment by Apple6050** [comment]
[plugins.zip](https://drive.google.com/file/d/1X9BkuW1R-VJVOzrKMuu29lnQyVQgVAMw/view?usp=sharing)

**Comment by qasde741** [comment]
감사합니다

**Comment by Apple6050** [comment]
이슈 닫아주세요
