### ISSUE TITLE
그냥

### ISSUE THREAD

**Issue by qasde741** [noonmaru/psychics#14]
.jar 파일을 그냥 구글 파일로 주시면 안돼나요
지금 보면 거이다 오픈소스로 적용못하는거 같은데

**Comment by qogusdn1017** [comment]
나중에 releases로 올라 올 수 있으니 기다리는게 좋을듯합니다.
또한 원하시면 직접 build하시는게 좋겠네요.

**Comment by 87898** [comment]
@qogusdn1017 혹시 드리면 저작권법 위반인가요?

**Comment by Apple6050** [comment]
@87898 GPL-3.0 License만 지키면 되므로 가능합니다

**Comment by 87898** [comment]
[plugins.zip](https://github.com/noonmaru/psychics/files/5316405/plugins.zip)

**Comment by qasde741** [comment]
wlrrka741@gmail.com 주세요

**Comment by qasde741** [comment]
> @qogusdn1017 혹시 드리면 저작권법 위반인가요?
wlrrka741@gmail.com 에 주세요
