### ISSUE TITLE
빌드어떻게 해요

### ISSUE THREAD

**Issue by habear** [noonmaru/psychics#15]
pllume님 글처럼 했는데 shadowJar를 어떻게 선택해야 되요?

**Comment by qogusdn1017** [comment]
JDK가 설치되어 있어야합니다. JDK 8을 권장합니다.
JAVA_HOME까지 설정하셨을 경우, 해당 디렉터리에 가서
gradlew clean shadowJar를 하여 빌드하신뒤
빌드가 성공적일경우 build/libs 디렉터리에서 얻으시면됩니다.

depend 플러그인들도 확인하세요.

(또한 비슷한 이유로 새 이슈를 만들지 말아주세요.)

**Comment by qogusdn1017** [comment]
#9 에서도 자세히 설명되어있으니 확인 부탁드립니다.

**Comment by qogusdn1017** [comment]
다른 이슈에서 많은 분들이 충분히 설명했으니 참고하시고 되실때 이슈 닫아주세요.

**Comment by gyusueng** [comment]
#9 에서 AutoReloader 1.0.1
InvFX 1.3.0
Tap 3.1.7
Kotlin-plugin 1.4.10
플러그인 이 필요하다 나왔는데, jar file 로 어떻게 변환 시키죠?

**Comment by Apple6050** [comment]
AutoReloader는 필수는 아닙니다

**Comment by qogusdn1017** [comment]
> #9 에서 AutoReloader 1.0.1
> InvFX 1.3.0
> Tap 3.1.7
> Kotlin-plugin 1.4.10
> 플러그인 이 필요하다 나왔는데, jar file 로 어떻게 변환 시키죠?

위의 내용처럼 gradlew를 이용해 빌드하거나,
noonmaru님이 이미 올리신 릴리즈를 쓰시면 될듯합니다.

**Comment by pikokr** [comment]
> #9 에서 AutoReloader 1.0.1
> InvFX 1.3.0
> Tap 3.1.7
> Kotlin-plugin 1.4.10
> 플러그인 이 필요하다 나왔는데, jar file 로 어떻게 변환 시키죠?

docker-compose.yml에 entrypoints에 있는 링크 확인해보세요(찾기 귀찮으면 쓰면되요)
