### ISSUE TITLE
질문 있습니다.

### ISSUE THREAD

**Issue by 87898** [noonmaru/psychics#16]
단지 전과 같이 단순한 빌드 문제, 그런 것이 아닙니다.

abilities 폴더의 샘플 어빌리티 (직선수리검, 블럭부메랑 등등..)  을 넣어 로드했습니다.

![AD](https://user-images.githubusercontent.com/58351496/94894822-17d78200-04c5-11eb-8a01-dc39a5859223.png)

후, psychics 폴더에 straight-shuriken 을 테스트하려고 y.yml을 생성하고, 코드를 이렇게 작성하였습니다.

![AD3](https://user-images.githubusercontent.com/58351496/94894869-32116000-04c5-11eb-9b75-e9150e7ed1f2.png)

그리고 보시는 것과 같이 오류가 났습니다. 아무런 오류 메시지 없이, abilites가 로드 안됩니다. 아무래도 제가 abilites: {} 의 구문을 잘못 적은 것 같은데요, 어떻게 하는지 알려주실 분 있으시다면 답변 감사드리겠습니다.

![2020-10-02_15 10 28](https://user-images.githubusercontent.com/58351496/94895058-8f0d1600-04c5-11eb-8ba8-93be8261e694.png)

**Comment by jedeop** [comment]
```yml
abilities:
  some-ability:
    ability: com.github.noonmaru.straight-shuriken
```
와 같이 작성하시면 해당 ability가 기본값으로 로드되는 듯 합니다.

**Comment by Apple6050** [comment]
@jedeop 감사합니다.

**Comment by 87898** [comment]
> ```yaml
> abilities:
>   some-ability:
>     ability: com.github.noonmaru.straight-shuriken
> ```
> 
> 와 같이 작성하시면 해당 ability가 기본값으로 로드되는 듯 합니다.

@jedeop 감사합니다. 덕분에 해결되었습니다. 근데, 문제가 하나 있습니다. 이것이 각별님의 버그 문제인지, 아니면 서버가 문제인지 잘 모르겠습니다. 어빌리티를 사용하면, 나선수리검은 구성하고 있는 삼지창이, 블럭 부메랑은 블럭이, 와카리마시타는 검들이 안보입니다. 그와중에 매직애로우는 작동이 잘 됩니다.

버킷 = paper-209
