### ISSUE TITLE
버젼은 몇으로 해야하나요?

### ISSUE THREAD

**Issue by ddhhssjj** [noonmaru/psychics#18]
저만 모르는게 아니라 다른분도 모르거나 헷갈려 할수도 있어서..

**Comment by OverseerK** [comment]
1.16.3

**Comment by ddhhssjj** [comment]
> 1.16.3

감사합니다

**Comment by blue1222** [comment]
@ddhhssjj 해결되었으면 이슈 닫아주세요....

**Comment by ddhhssjj** [comment]
@blue1222 죄송합니다 제가 이 사이트 처음이라 어떻게 끄는지 몰라요
