### ISSUE TITLE
능력 적용이 되지 않습니다

### ISSUE THREAD

**Issue by pikokr** [noonmaru/psychics#20]
![image](https://user-images.githubusercontent.com/68010770/94920477-5be07c00-04f1-11eb-90d4-117da771b3d6.png)

서버폴더/plugins/Psychics/abilities 폴더에 모두 빌드해서 넣었는데 로딩이 안되네요

**Comment by Apple6050** [comment]
서버폴더/plugins/Psychics/psychics에 Configuration 파일 넣으셨나요? @pikokr

**Comment by pikokr** [comment]
아하

**Comment by chipppppp** [comment]
> 아하

혹시 어떻게하는지 알려주실수 있나요 저도 저렇게 떠서;;
