### ISSUE TITLE
능력자 적용법, 능력자 만드는법

### ISSUE THREAD

**Issue by dragondy** [noonmaru/psychics#23]
플러그인 능력자를 어떻게 적용하나요?
또 어떻게 새로운 능력자를 만들 수 있나요?

**Comment by dragondy** [comment]
참고로
com.github.noonmaru.boomerang.jar 같은거는 다 구했습니다.

**Comment by Apple6050** [comment]
@dragondy 디스코드 Apple#1720로 알려드릴게요

**Comment by dragondy** [comment]
보냈습니다.

**Comment by dragondy** [comment]
혹시 질문하실거 있으신분은 들어오세요
https://discord.gg/dENFAPw

**Comment by dragondy** [comment]
닫습니다
