### ISSUE TITLE
요청드릴꺼

### ISSUE THREAD

**Issue by qasde741** [noonmaru/psychics#24]
매직스펠 리로드 처럼 플러그인 리로드 같은거 만들어서 해주시면 좋을거같아요

**Comment by Apple6050** [comment]
@qasde741 직접 만들어서 Pull request도 나쁘진 앟죠

**Comment by Apple6050** [comment]
[AutoReloader](https://github.com/noonmaru/AutoReloader)

**Comment by pikokr** [comment]
> [AutoReloader](https://github.com/noonmaru/Auto-Reloader)

저걸 플러그인 데이터 폴더 변경되는것도 반영돠게 햐면 될것 같네요

**Comment by noonmaru** [comment]
https://github.com/noonmaru/psychics/releases/tag/0.9.0
psychics reload 명령 추가되었습니다.
