### ISSUE TITLE
코딩 방법이랑 적용법 어디있나요...

### ISSUE THREAD

**Issue by earth-gl8** [noonmaru/psychics#25]
적용법이랑 그런거 찾고있는데 죄다 영어여서 어딨는지 모르겠네요 ㅜㅜ

**Comment by earth-gl8** [comment]
제가 깃허브 초보기도 해서 ;;

**Comment by qasde741** [comment]
플러그인
-https://drive.google.com/file/d/1X9BkuW1R-VJVOzrKMuu29lnQyVQgVAMw/view
코딩방법
-각님이 영상 올린데요

**Comment by earth-gl8** [comment]
@qasde741 아 그렇군요!!! 감사합니다!!!

**Comment by Apple6050** [comment]
쟤 구글 드라이브 링크가 퍼지고 있네요. @earth-gl8 @qasde741

**Comment by 87898** [comment]
> 쟤 구글 드라이브 링크가 퍼지고 있네요. @earth-gl8 @qasde741

혹시 코딩방법 아시나요

**Comment by hands8142** [comment]
여기는 코딩에 문제가 있거나 할 때 올리는 곳입니다 잡담은 하지 말아 주세요

**Comment by pikokr** [comment]
코딩 방법은 아직 안올라온것 같은데 적용법은 이 레포 위키에 올라와있어요

**Comment by hands8142** [comment]
이슈 닫아주세요

**Comment by earth-gl8** [comment]
넹....
