### ISSUE TITLE
플러그인

### ISSUE THREAD

**Issue by unhappiness** [noonmaru/psychics#27]
AutoReloader 1.0.1	InvFX 1.3.0	Tap 3.1.7	Kotlin-plugin 1.4.10 이거 다 어디있나요?

**Comment by eric236** [comment]
https://github.com/noonmaru 여기요

**Comment by unhappiness** [comment]
Jar 파일로 어떻게 다운 받죠?

**Comment by jini5012** [comment]
AutoReloader는 https://github.com/noonmaru/auto-reloader/releases/tag/1.0.1 여기에있고요
Tap은 https://github.com/noonmaru/tap/releases/tag/3.1.7 여기
InvFX는 https://github.com/noonmaru/invfx/releases/tag/1.3.0 여기
Kotlin은 https://github.com/noonmaru/kotlin-plugin/releases/tag/1.4.10 여기에 있어요.
