### ISSUE TITLE
능력 적용이 안되네요 

### ISSUE THREAD

**Issue by unhappiness** [noonmaru/psychics#28]
그 Psychics 폴더에 config ~~ 다 넣었는데도요

**Comment by unhappiness** [comment]
![image](https://user-images.githubusercontent.com/60720581/94988535-fbad1100-05a8-11eb-9937-e4c4bde1d410.png)
이렇게 했는데 ...

**Comment by eric236** [comment]
Psychics 폴더 -> abilities 폴더에 능력을 넣었나요?
