### ISSUE TITLE
코딩어떻게하나요?

### ISSUE THREAD

**Issue by shc0218** [noonmaru/psychics#29]
일단빌드는했는데 코딩방법을모르겠네여ㅠㅠㅠ

**Comment by gyusueng** [comment]
각별님이 영상 나중에 올리신데요

**Comment by TTINKER** [comment]
깃헙 issues는 프로젝트 개발에 관한 문제를 다루는 공간입니다.
질문 게시판으로 사용하지 말아 주세요.

**Comment by 87898** [comment]
이슈 닫아주세요.
