### ISSUE TITLE
gradlew.bat tasks 단계에서 빌드 실패가 떴습니다.

### ISSUE THREAD

**Issue by Sh4444rky** [noonmaru/psychics#30]
FAILURE: Build failed with an exception.

* What went wrong:
org/jetbrains/kotlin/cli/common/PropertiesKt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

JDK 15 사용 중.

**Comment by FullVery** [comment]
JDK 8버전을 이용하시면 해결됩니다

**Comment by pikokr** [comment]
JDK 11버전 사용해보세요

**Comment by Apple6050** [comment]
공식 WIKI 보시면 JDK 8이라고 나와 있습니다 @Sh4444rky @pikokr

**Comment by Sh4444rky** [comment]
감사합니다. 시도 후 성공시 닫겠습니다.

**Comment by Sh4444rky** [comment]
감사합니다. 잘 해결 되었습니다.
