### ISSUE TITLE
config 파일 작성을 어떻게 하나요?

### ISSUE THREAD

**Issue by raho38** [noonmaru/psychics#31]
어찌저찌 하여 능력자 플러그인을 넣고 실행결과, 정상적으로 명령어도 출력이 됩니다만,
어빌리티 폴더에 샘플 능력을 넣어보기도 하고, jar 파일을 넣어도 보고 여러가지를 다 시도해봤는데
능력 적용이 안돼더군요..
이슈 닫혀진것들도 찾아 보았는데 config 파일을 그 플러그인 폴더 안에 넣어야 한다고 하시는데
이 config 파일을 어떻게 작성을 하나요?

**Comment by 87898** [comment]
1. (serverRoot)/plugins/Psychics/psychics 로 간다.
2. <FileName>.yml 파일을 생성한다.
3. 서버를 reload한다.
4. <FileName>.yml 파일을 보면 정상적으로 무언가가 써져있을 것이다.
5. 다른 것은 문제가 없을 텐데, abilities: {} 이부분에서 문제가 생길 것이다.
```
abilities:
  (abilityName): // <- 아무거나 해도 괜찮습니다.
    ability: // (serverRoot)/plugins/Psychics/abilities 에 있는 능력. 예: (com.github.noonmaru.straight-shuriken)
```

적으면 된다.
6. 서버를 reload한다, /psychics attach <yourName> <psychicsName>
7. /psychics info <psychicsName>, 적용이 되어있다면, 성공이다.

**확인하시고 또다른 issue가 있으시다면 문제달아주세요.**

common-issue-1.
**Q.** 모든 것이 잘 되었는데, 직선수리검은 삼지창이, 와카리마시타는 검이, 블럭부메랑은 블럭이 안보입니다.
**A.** ProtocolLib 문제입니다. [lastSuccessBuild](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/) 를 받아주세요.

**Comment by 87898** [comment]
없다면 이슈 닫아주세요

**Comment by raho38** [comment]
display-name: name
health-bonus: 0.0
health-regen-per-tick: 0.0
mana: 0.0
mana-regen-per-tick: 0.0
mana-color: BLUE
description: []
abilities: {}

이클립스에서 yml 파일을 열어보니 이렇게 뜨는데 abilities: {}에서 {} 사이에 abilitiesName 하고 다적는건가요?
//는 끝에 써야하나요?

**Comment by 87898** [comment]
![a](https://user-images.githubusercontent.com/58351496/95024256-d9a4b300-06bc-11eb-9ded-a17d90b3f0bd.png)

abilities:
>>asdf: // **!! PRESS SPACEBAR FOR 2 TIMES !!**
>>>>ability: com.github.noon... // **!! ALSO PRESS SPACEBAR FOR 4 TIMES !!**

**Comment by raho38** [comment]
알려주신대로 했습니다만,
저렇게 하니 서버 로그 상에서 Not found com.github..... 이렇게 뜨고
아예 .yml 파일을 불러오는데 실패합니다.
당연하니거와 능력 이름을 쓰면 알 수 없는 인수입니다. 뜨는게 반복적입니다.
폴더에 파일이 전부 있고 어빌리티 폴더에도 준 그대로 존재합니다.
여러가지 시도를 하였는데도 불구하고 되질 않습니다.
어디가 잘못된건지 모르겟습니다.
![그림1](https://user-images.githubusercontent.com/72328745/95029275-04edc900-06e2-11eb-8aaf-309d1afa3580.png)
아니면 rjsguddlek88@naver.com으로 보내주십시오.

**Comment by pikokr** [comment]
ROOT/plugins/Psychics/abilities 폴더에 그 이름의 jar 파일이 있나요

**Comment by raho38** [comment]
네 정확한 이름으로 있습니다.
이상하게도 인식을 못하는지 지웠다가 다시 해보고도 했지만 되질 않네요.

**Comment by raho38** [comment]
어찌 저찌해서 적용을 하였습니다. 근데 비도(와카리마시타) 몬스터한테 데미지가 들어가질 않습니다.
