### ISSUE TITLE
gradlew.bat 에러

### ISSUE THREAD

**Issue by ysw827** [noonmaru/psychics#35]
FAILURE: Build failed with an exception.

* What went wrong:
org/jetbrains/kotlin/cli/common/PropertiesKt

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
자바 jdk는 11 jre는 8사용중

**Comment by eric236** [comment]
현재 0.7.1 jar가 나왔습니다. jar 파일 다운해서 쓰세요. 링크는 여기 https://github.com/noonmaru/psychics/releases/tag/0.7.1

**Comment by ysw827** [comment]
코드를 약간 비틀어 꼬아보기위한 준비중입니다

**Comment by ysw827** [comment]
자바 8로 하니 저 오류는 않뜨네요

**Comment by eric236** [comment]
해결되셨다면 이슈닫아주세요
