### ISSUE TITLE
부메랑 에러?

### ISSUE THREAD

**Issue by kirby0280** [noonmaru/psychics#36]
샘플 능력인 부메랑을 사용하는데 각님 영상에서는 양털들이 투사체 모양으로 나오는데 실행해 보니 안 나와서요...
어떻게 해야 하나요?

**Comment by eric236** [comment]
boomerang:
      boomerang-items:
      - ==: org.bukkit.inventory.ItemStack
        v: 2580
        type: RED_WOOL
      - ==: org.bukkit.inventory.ItemStack
        v: 2580
        type: YELLOW_WOOL
      - ==: org.bukkit.inventory.ItemStack
        v: 2580
        type: GREEN_WOOL
      - ==: org.bukkit.inventory.ItemStack
        v: 2580
        type: BLUE_WOOL
      - ==: org.bukkit.inventory.ItemStack
        v: 2580
        type: PURPLE_WOOL

이렇게 적으셨나요?

**Comment by kirby0280** [comment]
네

**Comment by kirby0280** [comment]
지금보니 와카리마시타도 안 보이네요;;

**Comment by kirby0280** [comment]
투사체의 모습이 다 보이지 않는것 같은데요

**Comment by kirby0280** [comment]
날아가는 모습이 보이지 않는데 엔티티가 데미지는 받네요

**Comment by eric236** [comment]
와카리마시타의 소환된 검은 보이나요?

**Comment by kirby0280** [comment]
아니요

**Comment by eric236** [comment]
flying-sword:
      projectile-ready-ticks: 8
      summon-ticks: 20
      projectile-ticks: 40
      projectile-speed: 4.0
      max-summon-count: 5
      ray-size: 1.0
      wooden:
        type: RANGED
        stats:
          ATK: 1.0
      stone:
        type: RANGED
        stats:
          ATK: 1.5
      iron:
        type: RANGED
        stats:
          ATK: 1.8
      golden:
        type: RANGED
        stats:
          ATK: 1.5
      diamond:
        type: RANGED
        stats:
          ATK: 2.0
      netherite:
        type: RANGED
        stats:
          ATK: 2.5
      bonus-damage-by-sharpness: 0.1
이렇게 적어 보시죠

**Comment by kirby0280** [comment]
그래도 안 보이네요;;

**Comment by eric236** [comment]
그냥 전체를 보여드릴게요

**Comment by eric236** [comment]
abilities:
  flying-sword:
    ability: com.github.noonmaru.flying-sword
    common:
      display-name: 비도
      type: ACTIVE
      cooldown-ticks: 10
      cost: 10.0
      interruptible: false
      range: 32.0
      supply-items: []
      description:
      - 검을 우클릭하여 비검을 소환합니다.
      - 최대 ${flying-sword.max-summon-count}개 소환 가능하며
      - 좌클릭으로 발사 할 수 있습니다.
      - 적에게 적중시 다음 피해를 입힙니다.
      - '나무: <wooden><wooden-damage>'
      - '돌: <stone><stone-damage>'
      - '철: <iron><iron-damage>'
      - '금: <golden><golden-damage>'
      - '다이아몬드: <diamond><diamond-damage>'
      - '네더라이트: <netherite><netherite-damage>'
      - 날카로움 인챈트당 ${flying-sword.bonus-damage-by-sharpness * 100}%의 추가 피해를 입힙니다.
    flying-sword:
      projectile-ready-ticks: 8
      summon-ticks: 20
      projectile-ticks: 40
      projectile-speed: 4.0
      max-summon-count: 5
      ray-size: 1.0
      wooden:
        type: RANGED
        stats:
          ATK: 1.0
      stone:
        type: RANGED
        stats:
          ATK: 1.5
      iron:
        type: RANGED
        stats:
          ATK: 1.8
      golden:
        type: RANGED
        stats:
          ATK: 1.5
      diamond:
        type: RANGED
        stats:
          ATK: 2.0
      netherite:
        type: RANGED
        stats:
          ATK: 2.5
      bonus-damage-by-sharpness: 0.1
display-name: flying-sword
health-bonus: 5.0
health-regen-per-tick: 0.5
mana: 100.0
mana-regen-per-tick: 0.3
mana-color: BLUE
description: []

**Comment by eric236** [comment]
abilities:
  flying-sword:
    ability: com.github.noonmaru.flying-sword
    common:
      display-name: 비도
      type: ACTIVE
      cooldown-ticks: 10
      cost: 10.0
      interruptible: false
      range: 32.0
      supply-items: []
      description:
      - 검을 우클릭하여 비검을 소환합니다.
      - 최대 ${flying-sword.max-summon-count}개 소환 가능하며
      - 좌클릭으로 발사 할 수 있습니다.
      - 적에게 적중시 다음 피해를 입힙니다.
      - '나무: <wooden><wooden-damage>'
      - '돌: <stone><stone-damage>'
      - '철: <iron><iron-damage>'
      - '금: <golden><golden-damage>'
      - '다이아몬드: <diamond><diamond-damage>'
      - '네더라이트: <netherite><netherite-damage>'
      - 날카로움 인챈트당 ${flying-sword.bonus-damage-by-sharpness * 100}%의 추가 피해를 입힙니다.
    flying-sword:
      projectile-ready-ticks: 8
      summon-ticks: 20
      projectile-ticks: 40
      projectile-speed: 4.0
      max-summon-count: 5
      ray-size: 1.0
      wooden:
        type: RANGED
        stats:
          ATK: 1.0
      stone:
        type: RANGED
        stats:
          ATK: 1.5
      iron:
        type: RANGED
        stats:
          ATK: 1.8
      golden:
        type: RANGED
        stats:
          ATK: 1.5
      diamond:
        type: RANGED
        stats:
          ATK: 2.0
      netherite:
        type: RANGED
        stats:
          ATK: 2.5
      bonus-damage-by-sharpness: 0.1
display-name: flying-sword
health-bonus: 5.0
health-regen-per-tick: 0.5
mana: 100.0
mana-regen-per-tick: 0.3
mana-color: BLUE
description: []

**Comment by eric236** [comment]
참고로 마나도 제가 설정한데로 바뀝니다

**Comment by eric236** [comment]
abilities:
  boomerang:
    ability: com.github.noonmaru.boomerang
    common:
      display-name: 부메랑
      type: ACTIVE
      casting-ticks: 5
      interruptible: false
      damage:
        type: RANGED
        stats:
          ATK: 1.0
      wand:
        v: 2580
        type: GOLD_INGOT
      supply-items: []
      description:
      - 지정한 방향으로 부메랑을 빠르게 발사합니다.
      - 발사된 부메랑은 부딪힌 적에게 피해를 입히고
      - 천천히 돌아옵니다.
      - 부메랑을 회수시 다시 사용 할 수 있습니다.
      cooldown-ticks: 2
    boomerang:
      boomerang-items:
      - ==: org.bukkit.inventory.ItemStack
        v: 2580
        type: RED_WOOL
      - ==: org.bukkit.inventory.ItemStack
        v: 2580
        type: YELLOW_WOOL
      - ==: org.bukkit.inventory.ItemStack
        v: 2580
        type: GREEN_WOOL
      - ==: org.bukkit.inventory.ItemStack
        v: 2580
        type: BLUE_WOOL
      - ==: org.bukkit.inventory.ItemStack
        v: 2580
        type: PURPLE_WOOL
      projectile-launch-speed: 7.0
      projectile-ticks: 200
      projectile-returning-ticks: 8
      projectile-returning-speed: 0.4
      knockback: 0.75
      ray-size: 0.3
display-name: boomerang
health-bonus: 5.0
health-regen-per-tick: 0.8
mana: 100.0
mana-regen-per-tick: 1.0
mana-color: BLUE
description: []

부메랑 입니다

**Comment by kirby0280** [comment]
이제 소환도 안되는데요?

**Comment by eric236** [comment]
기존에 있던 것들은 지웠나요?

**Comment by kirby0280** [comment]
네

**Comment by kirby0280** [comment]
부메랑은 여전히 투사체가 보이지 않네요

**Comment by eric236** [comment]
이상하네요. 전 되는데...

**Comment by kirby0280** [comment]
투사체 모양만 나오게 하면 될텐데 어떻게 나오게 하는지 모르겠네요;

**Comment by eric236** [comment]
[abilites.zip](https://github.com/noonmaru/psychics/files/5324877/abilites.zip)

**Comment by eric236** [comment]
여기에 와카리미시타와 부메랑 yml을 넣어놨습니다

**Comment by eric236** [comment]
이제 되나요?

**Comment by Apple6050** [comment]
@kirby0280 @eric236 ProtocolLib 업데이트 하세요

**Comment by Apple6050** [comment]
LastSucessfulBuild 사용하세요

**Comment by eric236** [comment]
네

**Comment by Apple6050** [comment]
[LastSucessfulBuild](https://ci.dmulloy2.net/job/ProtocolLib/lastSuccessfulBuild/artifact/target/ProtocolLib.jar)

**Comment by kirby0280** [comment]
아 이제 되네요
이슈 닫겠습니다
