### ISSUE TITLE
와카리마시타(비도) 데미지, 매직에로우  오류

### ISSUE THREAD

**Issue by raho38** [noonmaru/psychics#37]
여러분들이 도와주셔서 .yml로 하여 와카리마시타(비도),직선수리검,부메랑 까지 어떻게 어찌저찌 적용을 시켰습니다.
하지만 여기서 문제가 발생했습니다.
다른 것들, 직선수리검과 부메랑은 데미지와 레벨별로 데미지가 강해지는 것들은 전부 완벽하게 됩니다만,
요놈 이 와카리마시타(비도) 요놈은 데미지가 들어가질 않더군요.
요리 맞춰도 저리맞춰도 전혀 데미지가 가질 않습니다.
다른분이 남겨준 이슈에서도 참고를 해보았으나 결과는 같았습니다.
검 갯수 늘린게 문제인가 싶어서 기존으로 했으나 그대로입니다.

또 매직 에로우는 아예 적용이 되질 않는데
어떻게 해야해야 하나요?

**Comment by yoomath2018** [comment]
[Psychics.zip](https://github.com/noonmaru/psychics/files/5325425/Psychics.zip)
