### ISSUE TITLE
마인크래프트에서 무슨 능력을 어떻게 사용하나요?

### ISSUE THREAD

**Issue by jini5012** [noonmaru/psychics#4]
마인크래프트에서 무슨 능력을 어떻게 사용하나요?

**Comment by jinhoftyu** [comment]
혹시 physics-master 0.4.5 다운로드 하셔서 빌드해서 서버에 플러그인을 적용시켜는 보셨는지요?

**Comment by jini5012** [comment]
네 그랬어요

**Comment by jini5012** [comment]
> 혹시 physics-master 0.4.5 다운로드 하셔서 빌드해서 서버에 플러그인을 적용시켜는 보셨는지요?

physics가 아니라 psychics 입니다

**Comment by jinhoftyu** [comment]
아 맞네요ㅋㅋ 오타

**Comment by jini5012** [comment]
@noonmaru 저기요?

**Comment by zlfn** [comment]
이 플러그인 자체에 들어있는 능력은 없습니다.
능력자 플러그인을 만드는 API이기 때문에 능력 쓰실려면 직접 프로그래밍 하셔야 됩니다.
https://www.youtube.com/watch?v=-7udCsZK9Pg 참고하세요.

**Comment by OverseerK** [comment]
때가 되면 알아서 공개하시겠죠 기다려봐요

**Comment by jini5012** [comment]
오오옷
