### ISSUE TITLE
투사체

### ISSUE THREAD

**Issue by herotoma** [noonmaru/psychics#41]
투사체가 안보이고 투사체 입자만 보이는데 해결법 아시는분 있나요

**Comment by eric236** [comment]
저도 어제 까진 안그랬는데 이상하네요

**Comment by raho38** [comment]
ProtocolLip 문제일 수 있습니다. 최신버전으로 다운로드 해보세요

**Comment by eric236** [comment]
ProtocolLip 최신버전 사용하니 됩니다

**Comment by Apple6050** [comment]
ProtocoolLip X ProtocolLib O

**Comment by Apple6050** [comment]
@raho38 @eric236
