### ISSUE TITLE
intelliJ에서 스킬 샘플을 구성하는데 오류가 납니다 해결방법이 있을까요?

### ISSUE THREAD

**Issue by sgkill6** [noonmaru/psychics#42]
intelliJ에서 스킬 샘플을 구성하는데 오류가 납니다 해결방법이 있을까요?

Could not find org.spigotmc:spigot:1.16.3-R0.1-SNAPSHOT.
Searched in the following locations:
  - https://repo.maven.apache.org/maven2/org/spigotmc/spigot/1.16.3-R0.1-SNAPSHOT/maven-metadata.xml
  - https://repo.maven.apache.org/maven2/org/spigotmc/spigot/1.16.3-R0.1-SNAPSHOT/spigot-1.16.3-R0.1-SNAPSHOT.pom
  - https://papermc.io/repo/repository/maven-public/org/spigotmc/spigot/1.16.3-R0.1-SNAPSHOT/maven-metadata.xml
  - https://papermc.io/repo/repository/maven-public/org/spigotmc/spigot/1.16.3-R0.1-SNAPSHOT/spigot-1.16.3-R0.1-SNAPSHOT.pom
  - https://jitpack.io/org/spigotmc/spigot/1.16.3-R0.1-SNAPSHOT/maven-metadata.xml
  - https://jitpack.io/org/spigotmc/spigot/1.16.3-R0.1-SNAPSHOT/spigot-1.16.3-R0.1-SNAPSHOT.pom
  - file:/C:/Users/sgkil/.m2/repository/org/spigotmc/spigot/1.16.3-R0.1-SNAPSHOT/maven-metadata.xml
  - file:/C:/Users/sgkil/.m2/repository/org/spigotmc/spigot/1.16.3-R0.1-SNAPSHOT/spigot-1.16.3-R0.1-SNAPSHOT.pom
Required by:
    project :abilities:sample

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by asheept** [comment]
https://www.spigotmc.org/wiki/buildtools/

build 해주세용
