### ISSUE TITLE
빌드를 못하겠네요

### ISSUE THREAD

**Issue by xodms1722** [noonmaru/psychics#48]
이곳에서 각별님이 아니면 빌드를 할 수 있는 사람이 몇 없지 않습니까?
저도 마찬가지고요
빌드 된 파일을 받을 수 있을까요?

**Comment by yoomath2018** [comment]
코드 폴더로 가서 cmd를 여신 후 gradlew build라고 하면 build라는 폴더에 .jar 파일이 생성됩니다

**Comment by OverseerK** [comment]
릴리즈에 jar파일 있는데.. (__)

**Comment by xodms1722** [comment]
코드 폴더가 어디인가요?

**Comment by xodms1722** [comment]
빌드를 실패했다네요

**Comment by xodms1722** [comment]
> Task :psychics-common:compileKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':psychics-common:compileKotlin'.
> Kotlin could not find the required JDK tools in the Java installation 'C:\Program Files\Java\jre1.8.0_201' used by Gradle. Make sure Gradle is running on a JDK, not JRE.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 43s
3 actionable tasks: 3 executed

**Comment by xodms1722** [comment]
JDK를 설치해야 하는군요
버전은 몇으로 해야하나요?

**Comment by yoomath2018** [comment]
버전은 아마도 Version 8 Update 261면 되는것 같습니다
그리고 환경변수에도 java jdk path를 추가해줘야 합니다

**Comment by xodms1722** [comment]
다시 했지만 빌드 실패네요

**Comment by xodms1722** [comment]
> Task :psychics-common:compileKotlin FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':psychics-common:compileKotlin'.
> Kotlin could not find the required JDK tools in the Java installation 'I:\Java Jdk' used by Gradle. Make sure Gradle is running on a JDK, not JRE.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
3 actionable tasks: 3 executed

**Comment by xodms1722** [comment]
Version 8 Update 261로 설치했지만 실패하네요

**Comment by yoomath2018** [comment]
bin 폴더로 연결해줘야합니다

**Comment by yoomath2018** [comment]
JAVA_HOME : I:\Java Jdk\(버전)\bin

**Comment by eric236** [comment]
여기 있습니다 
https://github.com/noonmaru/psychics/releases/tag/0.7.2

**Comment by xodms1722** [comment]
감사합니다

**Comment by xodms1722** [comment]
플러그인 적용법은 뭔가요?

**Comment by xodms1722** [comment]
bin으로 연결하면 파일을 찾을 수 없다네요
(Java Jdk에 바로 설치했습니다 버전 파일 없이 바로 있어요)

**Comment by patrick-mc** [comment]
Java 설치 시 JAVA_HOME 환경변수는 jdk의 루트 폴더, 
Path 환경변수에 jdk의 bin 폴더를 넣으셔야 합니다.

IntelliJ에서도 gradle이 사용하는 jdk에 해당 JAVA_HOME을 연결 할 필요가 있을수도 있습니다.

**Comment by xodms1722** [comment]
이미 이렇게 되어 있습니다

**Comment by Tilto0822** [comment]
> 플러그인 적용법은 뭔가요?

서버에 적용하는 것을 말씀하시는 거면, 서버의 plugins폴더에
https://github.com/noonmaru/psychics/wiki/%EC%9D%98%EC%A1%B4%EC%84%B1-%ED%94%8C%EB%9F%AC%EA%B7%B8%EC%9D%B8-%EC%84%A4%EC%B9%98
위 링크에서 다운받은 플러그인과 함께 넣으면 적용됩니다.
