### ISSUE TITLE
능력을 만들고(이미 만들어 놓음) 적용하는법 이 뭐죠?

### ISSUE THREAD

**Issue by sgkill6** [noonmaru/psychics#49]

**Comment by jini5012** [comment]
서버 파일\plugins\Psychics\ability라고 되있는 곳에 능력을 넣고
서버 파일\plugins\Psychics\psychics라고 되있는곳에는 boomerang.yml, flying-sword.yml, magic-arrow.yml, straight-shuriken.yml을 만드시면 됩니다.그럼 적용이 되고요
