### ISSUE TITLE
위키에 Event대로 따라하고있는데 서버에 적용이안됩니다..

### ISSUE THREAD

**Issue by shane5828** [noonmaru/psychics#50]
1.java.lang.IllegalStateException: Not found ability com.github.shane5828.myability 라고 서버엔 뜨고요

IntelliJ에선 똑같이 따라해봣는데 MyAbility랑 onPlayerInteract는 never used가 나오고있습니다..

아래는 제가 그대로 복사해온겁니다. 혹시 잘못쓴게있을까요
------------------------------------------------------------------
package foo.tutorial.psychics.ability

import com.github.noonmaru.psychics.Ability
import com.github.noonmaru.psychics.AbilityConcept
import org.bukkit.event.EventHandler
import org.bukkit.event.Listener
import org.bukkit.event.block.Action
import org.bukkit.event.player.PlayerInteractEvent

class MyAbility : Ability<AbilityConcept>() {
    override fun onEnable() {
        psychic.registerEvents(MyAbilityListener())
    }
}

class MyAbilityListener : Listener {
    @EventHandler
    fun onPlayerInteract(event: PlayerInteractEvent) {
        if (event.action == Action.LEFT_CLICK_AIR) {
            event.player.sendMessage("능력 사용자가 왼손을 휘둘렀다.")
        }
    }
}

2. event에 8번에보면 group과 author를 변경하라고하시는데 그 이유가 궁금하고 어떻게 바꿔야하는지
궁금합니다.

3. yml에 입력할때 그대로
abilities:
  myfirstability:
    ability: .myability 로 입력했는데도 1번같은 오류가 나옵니다

혹시 yml에 따로 뭘 더 적어야하나요? Event칸에보면 저대로 입력하셨던데

길게질문해서 죄송합니다..

**Comment by yoomath2018** [comment]
일단 1번 Function "onPlayerInteract" is never used 은 맞구요,  
`class MyAbility : Ability<AbilityConcept>() {
    override fun onEnable() {
        psychic.registerEvents(MyAbilityListener());
    }
}`
이렇게 적어야 합니다.
AbilityConcept을 빼먹으셨습니다.
그리고 
@eventhandler 를 @EventHandler로 바꾸셔야 합니다.

그다음 2번은 group은 jar 압축 파일 이름일 것 같습니다
예시 (제 이름은 yoomath2018이니까 com.github.yoomath2018.(능력이름).jar)이 될것 같네요
Author는 저도 모르는 부분입니다...

3번은 .myability 부분을 com.github.shane5828.MyAbility
그러니까 이 플러그인은 대소문자를 구분합니다. myability가 아니라 MyAbility가 되어야 할 듯 합니다.

**Comment by shane5828** [comment]
아래처럼 써서 새로 빌드해서 넣었는데도 적용이 안돼네요 왜그럴까요

package foo.tutorial.psychics.ability

import com.github.noonmaru.psychics.Ability
import com.github.noonmaru.psychics.AbilityConcept
import org.bukkit.event.EventHandler
import org.bukkit.event.Listener
import org.bukkit.event.block.Action
import org.bukkit.event.player.PlayerInteractEvent

class MyAbility : Ability<AbilityConcept>() {
    override fun onEnable() {
        psychic.registerEvents(MyAbilityListener())
    }
}

class MyAbilityListener : Listener {
    @EventHandler
    fun onPLayerInteract(event: PlayerInteractEvent) {
        if (event.action == Action.LEFT_CLICK_AIR) {
            event.player.sendMessage("왼손을 휘둘렀다")
        }
    }
}

**Comment by yoomath2018** [comment]
package foo.tutorial.psychics.ability

import com.github.noonmaru.psychics.Ability
import com.github.noonmaru.psychics.AbilityConcept
import org.bukkit.event.EventHandler
import org.bukkit.event.Listener
import org.bukkit.event.block.Action
import org.bukkit.event.player.PlayerInteractEvent

class MyAbility : Ability(AbilityConcept) {
override fun onEnable() {
psychic.registerEvents(MyAbilityListener())
}
}

class MyAbilityListener : Listener {
@eventhandler
fun onPLayerInteract(event: PlayerInteractEvent) {
if (event.action == Action.LEFT_CLICK_AIR) {
event.player.sendMessage("왼손을 휘둘렀다")
}
}
}
