### ISSUE TITLE
wand 설정법

### ISSUE THREAD

**Issue by ohgi07** [noonmaru/psychics#53]
Casting에서 AbilityConcept.wand로 설정할수 있다고는 하는데 어떻게 설정해야할지 모르겠습니다.
제가 금조각(gold_nugget)을 설정하고 싶어서
class StarpieceConcept: AbilityConcept() {
    init {
        displayName = "별조각"
        cooldownTicks = 2 // 0.1초
        cost = 1.0
        wand = gold_nugget
    }
}
이렇게 설정했는데 안되네요 ""이거, ''이거 다 붙여봤습니다
그런데 안되네요 어떻게 설정해야하나요?

**Comment by yoomath2018** [comment]
ItemStack(Material.GOLD_NUGGET) 이렇게  쓰셔야 합니다

**Comment by superjoy0502** [comment]
```kotlin
class StarpieceConcept: AbilityConcept() {
    init {
        displayName = "별조각"
        cooldownTicks = 2 // 0.1초
        cost = 1.0
        wand = ItemStack(Material.GOLD_NUGGET)
    }
}
```
로 문제가 해결될겁니다.

[AbilityConcept.kt](https://github.com/noonmaru/psychics/blob/master/psychics-common/src/main/kotlin/com/github/noonmaru/psychics/AbilityConcept.kt)를 보시면 wand는 ItemStack 변수입니다.
앞으로도 변수 타입을 차마고하셔서 작성하시면 작업이 훨씬 수월해지실겁니다.

**Comment by ohgi07** [comment]
@superjoy0502 감사합니다 해결되었습니다
