### ISSUE TITLE
별님이 해주신 그 와칼이마시타 같은건 어떻게 적용하나요 

### ISSUE THREAD

**Issue by solgu9080** [noonmaru/psychics#54]
적용법을 아얘모르겠네요 ㅠ

**Comment by superjoy0502** [comment]
[이 링크](https://github.com/noonmaru/psychics/wiki/%EA%B5%AC%EC%84%B1%ED%95%98%EA%B8%B0)를 참고하시면 됩니다. :)

**Comment by solgu9080** [comment]
제가 저거 파일을 만드는법을 모르는데..

**Comment by yoomath2018** [comment]
1.확장명이 보이는지 확인하세요
2.Psychics/psychics/ 에 우클릭>새로 만들기> 새로운 텍스트 파일
3.이름을 sample.yml로 바꾸세요 (확장명 체크)
4.자신의 코드 에디터로 파일을 여세요
abilities:
    (자신이 원하는 이름):
        ability: (이름에서 .jar 을 뺀 abilities의 폴더 안에 있는 jar의 이름을 넣기)
5.ability.zip을 다운받아 abilities폴더 안에 .jar파일을 넣으세요
6.서버를 재시작하세요
