### ISSUE TITLE
Fake entity nbt 수정 하는법

### ISSUE THREAD

**Issue by ohgi07** [noonmaru/psychics#55]
Fake entity 아머스탠드 nbt를 어떻게 수정하나요?
예를 들어 안보이게 하거나 머리에 아이탬을 씌우거나 이런거요

**Comment by noonmaru** [comment]
FakeEntity#updateMetadata
FakeEntity#updateEquipment

**Comment by ohgi07** [comment]
@noonmaru 정말 감사합니다 ㅠㅠ

**Comment by ohgi07** [comment]
@noonmaru fakeEntity?.updateMetadata<> {Invisible = true}
                                                                     ^여기에 오류가 뜨는데 뭘 넣어야하나요?

**Comment by ohgi07** [comment]
@noonmaru fakeEntity?.updateMetadata<> {Invisible = true}
<>여기에 오류가 뜨는데 뭘 넣어야하나요?

**Comment by noonmaru** [comment]
https://github.com/noonmaru/psychics/wiki/Fake-entity
