### ISSUE TITLE
마법 화살 복제 됩니다

### ISSUE THREAD

**Issue by joeyPark8** [noonmaru/psychics#56]
마법화살 마우스 가운데 버튼 눌러서 복제하면 복제됩니다

**Comment by joeyPark8** [comment]
또 활을 상자에 넣고 다시 공급 받고 하면 많이 얻을수 있습니다

**Comment by superjoy0502** [comment]
안녕하세요.

능력자는 기본적으로 서바이벌 모드에서 사용하는 플러그인이라 그것까지 막을 필요성이 거의 없다고 생각됩니다.
또한, [막는 것이 거의 불가능](https://www.spigotmc.org/threads/disabling-middle-click-in-creative.138830/)합니다.

참고가 되셨길 바라겠습니다.

P. S. 어차피 활에 Infinite 인챈트가 있어서 복제를 해도 하는 사람 인벤토리 공간 손해입니다. 화살 하나만 있으면 전부 되기 때문이죠.

**Comment by superjoy0502** [comment]
안녕하세요.

먼저, 능력자 플러그인은 서바이벌 모드를 기준으로 하는 플러그인입니다. 즉, 영상에서 말하는 "아이템 복제"는 서바이벌 모드를 기준으로 말하는 것 입니다.
그리고, 해당 기능은 플러그인 차원에서 막는 것이 [거의 불가능합니다](https://www.spigotmc.org/threads/disabling-middle-click-in-creative.138830/).

참고가 되셨길 바랍니다.

P. S. 어차피 복제해도 자기 인벤토리 손해라는 것이 아이러니한 점입니다.
