### ISSUE TITLE
커맨드 블럭 관련

### ISSUE THREAD

**Issue by Sh4444rky** [noonmaru/psychics#57]
커맨드 블럭으로 입력할 경우, 특정 플레이어 닉네임 지목이 아닌 이상 안됩니다. @s 나 @p 같은 것이 작동하지 않습니다.

**Comment by noonmaru** [comment]
명령어 추천기능은 부족하지만 일단 구현해두었습니다.
https://github.com/noonmaru/psychics/releases/tag/0.9.0
