### ISSUE TITLE
질문

### ISSUE THREAD

**Issue by Apple6050** [noonmaru/psychics#6]
**사용 방법좀 README.md에 추가해주세요** @noonmaru

**Comment by Apple6050** [comment]
@noonmaru ** 빌드는 가능한데 빌드 완료 후 어떻게 사용하는지 궁금합니다 **

**Comment by pllume** [comment]
@Apple6050 근데 빌드 어떻게 하나요 지금 0.6.0 으로 하고 있는데 안되드라고요

**Comment by Apple6050** [comment]
@pllume 디스코드 ID 알려주세요 예시 ) XXXXX#0000

**Comment by Apple6050** [comment]
@pllume Apple6050#1781

**Comment by pllume** [comment]
친추 걸었습니다.

**Comment by Apple6050** [comment]
오늘 올라온 영상 봤습니다.
