### ISSUE TITLE
이건 어떻게 하죠

### ISSUE THREAD

**Issue by PlayingNuro** [noonmaru/psychics#63]
이제 /plugins/psychics/abilities/ 에 능력들을 넣고 위키에서 작성하기를 하려고 하는데 작성을 어떻게 하죠..

**Comment by moJobSrc** [comment]
/plugins/Psychics/psychics/ 위치로 이동하셔서
sample.yml 을 만드신후
```
abilities:
  sample:
    ability: com.github.noonmaru.boomerang (어빌리티 이름)
```
작성해주시면됩니다.
그후 저장후 서버켜주시면 어빌리티가 정삭적으로 인식될껍니다.

**Comment by superjoy0502** [comment]
파일 이름과 위 내용 중에 sample은 자기가 원하는 이름으로 치환하셔도 됩니다.

**Comment by PlayingNuro** [comment]
감사합니당
