### ISSUE TITLE
질문이 있습니다

### ISSUE THREAD

**Issue by alstn8022** [noonmaru/psychics#64]
Hello Ability! 단계 똑같이 해서 build 하고 서버에 적용시키니까 - (group).(projectname) vunspecified라고 나옵니다. 뭐가 잘못된건가요?

**Comment by yoomath2018** [comment]
잘못 된 것은 아닙니다
그냥 버전을 적지 않아 생긴 일 같습니다

**Comment by alstn8022** [comment]
아 감사합니다

**Comment by yoomath2018** [comment]
@alstn8022 해결되었으면 이슈 닫아주세요
