### ISSUE TITLE
부메랑과 직선수리검은 적용이 됐는데 와카리마시타와 매직 아처는 적용이 안되는 상황을 겪고 있습니다.

### ISSUE THREAD

**Issue by hb3810** [noonmaru/psychics#66]
java.lang.IllegalArgumentException: Failed to render template token ${flying-sword.bonus-damage-by-sharpness * 100}
[19:09:11 WARN]:        at com.github.noonmaru.psychics.tap.template.TemplateSupportKt.renderTemplates(TemplateSupport.kt:77)
[19:09:11 WARN]:        at com.github.noonmaru.psychics.tap.template.TemplateSupportKt.renderTemplatesAll(TemplateSupport.kt:31)
[19:09:11 WARN]:        at com.github.noonmaru.psychics.AbilityConcept.initialize$psychics_common(AbilityConcept.kt:196)[19:09:11 WARN]:        at com.github.noonmaru.psychics.PsychicManager.loadPsychics$psychics_common(PsychicManager.kt:229)
[19:09:11 WARN]:        at com.github.noonmaru.psychics.plugin.PsychicPlugin.loadModules(PsychicPlugin.kt:72)
[19:09:11 WARN]:        at com.github.noonmaru.psychics.plugin.PsychicPlugin.onEnable(PsychicPlugin.kt:52)
[19:09:11 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[19:09:11 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[19:09:11 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[19:09:11 WARN]:        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:501)
[19:09:11 WARN]:        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:415)
[19:09:11 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468)
[19:09:11 WARN]:        at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:237)
[19:09:11 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939)
[19:09:11 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[19:09:11 WARN]:        at java.base/java.lang.Thread.run(Thread.java:832)
[19:09:11 WARN]: Caused by: java.lang.IllegalArgumentException: Failed to evaluate 0.1 * 100
[19:09:11 WARN]:        at com.github.noonmaru.psychics.tap.template.Template$Expression.renderValue(TemplateSupport.kt:174)
[19:09:11 WARN]:        at com.github.noonmaru.psychics.tap.template.TemplateSupportKt.renderTemplates(TemplateSupport.kt:71)
[19:09:11 WARN]:        ... 15 more
[19:09:11 WARN]: [Psychics] Failed to load Psychic flying-sword.yml
[19:09:11 WARN]: java.lang.IllegalArgumentException: Failed to render template token ${magic-archer.arrow-delay-ticks / 20.0}
[19:09:11 WARN]:        at com.github.noonmaru.psychics.tap.template.TemplateSupportKt.renderTemplates(TemplateSupport.kt:77)
[19:09:11 WARN]:        at com.github.noonmaru.psychics.tap.template.TemplateSupportKt.renderTemplatesAll(TemplateSupport.kt:31)
[19:09:11 WARN]:        at com.github.noonmaru.psychics.AbilityConcept.initialize$psychics_common(AbilityConcept.kt:196)[19:09:11 WARN]:        at com.github.noonmaru.psychics.PsychicManager.loadPsychics$psychics_common(PsychicManager.kt:229)
[19:09:11 WARN]:        at com.github.noonmaru.psychics.plugin.PsychicPlugin.loadModules(PsychicPlugin.kt:72)
[19:09:11 WARN]:        at com.github.noonmaru.psychics.plugin.PsychicPlugin.onEnable(PsychicPlugin.kt:52)
[19:09:11 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[19:09:11 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[19:09:11 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[19:09:11 WARN]:        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:501)
[19:09:11 WARN]:        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:415)
[19:09:11 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.loadWorld(MinecraftServer.java:468)
[19:09:11 WARN]:        at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:237)
[19:09:11 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939)
[19:09:11 WARN]:        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[19:09:11 WARN]:        at java.base/java.lang.Thread.run(Thread.java:832)
[19:09:11 WARN]: Caused by: java.lang.IllegalArgumentException: Failed to evaluate 8 / 20.0
[19:09:11 WARN]:        at com.github.noonmaru.psychics.tap.template.Template$Expression.renderValue(TemplateSupport.kt:174)
[19:09:11 WARN]:        at com.github.noonmaru.psychics.tap.template.TemplateSupportKt.renderTemplates(TemplateSupport.kt:71)
[19:09:11 WARN]:        ... 15 more
[19:09:11 WARN]: [Psychics] Failed to load Psychic magic-arrow.yml
여기 까지 와카리 마시타와 매직아처에 관한 문제고요

paper-230이고, 플러그인은 noonmaru님이 wiki에 올려주신 버젼 그대로고요. 다른 플러그인은 적용하지 않았습니다.

abilities:
  sample:
   ability: com.github.noonmaru.flying-sword

abilities:
  sample:
    ability: com.github.noonmaru.magic-arrow
라고 입력 후 실행하였지만 적용되지 않았습니다.

**Comment by dinooo5252** [comment]
부메랑과 직선수리검은 최신 릴리즈를 다운로드해보세요. 나머지는 저도 잘 모르겠네요.

**Comment by superjoy0502** [comment]
파일 및 폴더 구조와 paper 및 기타 플러그인 버젼을 제공해주시면 감사하겠습니다.
그리고 두 yml 파일의 내용도 첨부해 주실 수 있을까요?
도움을 드릴 수 있을 것 같습니다.

**Comment by hb3810** [comment]
넵 지금은 시간이 조금 늦어 시간나는 대로 최대한 빨리 첨부하겠습니다

**Comment by hb3810** [comment]
> 파일 및 폴더 구조와 paper 및 기타 플러그인 버젼을 제공해주시면 감사하겠습니다.
> 그리고 두 yml 파일의 내용도 첨부해 주실 수 있을까요?
> 도움을 드릴 수 있을 것 같습니다.

첨부해보았습니다

**Comment by superjoy0502** [comment]
버젼을 넘버링으로 말씀해주시길 바랍니다. 위키는 가장 최신버젼으로 연결되지만 작성자 분께서 언제 다운로드를 받았는지, 다시 다운로드를 받으셨는지 확인이 불가능하기 때문에 가급적이면 넘버링으로 전달해주세요.

**Comment by hb3810** [comment]
> 버젼을 넘버링으로 말씀해주시길 바랍니다. 위키는 가장 최신버젼으로 연결되지만 작성자 분께서 언제 다운로드를 받았는지, 다시 다운로드를 받으셨는지 확인이 불가능하기 때문에 가급적이면 넘버링으로 전달해주세요.

kotlin은 1.14.10 invFX는 1.3.0 protocolLib은 4.6.0-SNAPSHOT-b480 입니다

**Comment by hb3810** [comment]
> psychics의 버젼은 몇이죠?

0.9.2버젼입니다

**Comment by superjoy0502** [comment]
어빌리티 버젼도 같나요?

**Comment by hb3810** [comment]
> 어빌리티 버젼도 같나요?

어빌리티는 모두 0.0.1 아닌가요?
0.9.2와 함께 다운로드하긴 했습니다

**Comment by realteusu** [comment]
> abilities:
> sample:
> ability: com.github.noonmaru.flying-sword
> 
> abilities:
> sample:
> ability: com.github.noonmaru.magic-arrow

현재 보시면 `sample`이 두개가 겹치는데 다 다르게 하셔야합니다.

그리고 yml 한개마다 abilities가 한개씩 있어야하는걸로 알고있습니다.

예시:
```yml
abilities:
  sample:
    ability: com.github.noonmaru.boomerang
  second-sample:
    ability: com.github.noonmaru.magic-arrow
```

**Comment by hb3810** [comment]
> > abilities:
> > sample:
> > ability: com.github.noonmaru.flying-sword
> > abilities:
> > sample:
> > ability: com.github.noonmaru.magic-arrow
> 
> 현재 보시면 `sample`이 두개가 겹치는데 다 다르게 하셔야합니다.
> 
> 그리고 yml 한개마다 abilities가 한개씩 있어야하는걸로 알고있습니다.
> 
> 예시:
> 
> ```yaml
> abilities:
>   sample:
>     ability: com.github.noonmaru.flying-sword
>   second-sample:
>     ability: com.github.noonmaru.magic-arrow
> ```

감사합니다 이따가 시도해보고 해결되면 이슈닫겠습니다

**Comment by hb3810** [comment]
> > abilities:
> > sample:
> > ability: com.github.noonmaru.flying-sword
> > abilities:
> > sample:
> > ability: com.github.noonmaru.magic-arrow
> 
> 현재 보시면 `sample`이 두개가 겹치는데 다 다르게 하셔야합니다.
> 
> 그리고 yml 한개마다 abilities가 한개씩 있어야하는걸로 알고있습니다.
> 
> 예시:
> 
> ```yaml
> abilities:
>   sample:
>     ability: com.github.noonmaru.flying-sword
>   second-sample:
>     ability: com.github.noonmaru.magic-arrow
> ```

해결이 되지 않았습니다. 혹시 더 자세한 해결법을 알려주실 수 있으신가요?

**Comment by realteusu** [comment]
yml 어떻게 작성하셨는지 올려주실수 있으신가요?

**Comment by hb3810** [comment]
> yml 어떻게 작성하셨는지 올려주실수 있으신가요?

abilities:
sample:
ability: com.github.noonmaru.flying-sword

abilities:
sample:
ability: com.github.noonmaru.magic-arrow

abilities:
sample:
ability: com.github.noonmaru.boomerang

abilities:
sample:
ability: com.github.noonmaru.straight-shuriken
이라고 썼는데 부메랑과 직선 수리검만 적용되고 비도와 마법화살은 적용되지 않았습니다.

**Comment by realteusu** [comment]
각각 쓰신건가요 한 파일에 쓰신건가요?

**Comment by hb3810** [comment]
> 각각 쓰신건가요 한 파일에 쓰신건가요?

각각 썼습니다

**Comment by realteusu** [comment]
각각 쓰시더라도 `sample`이 겹쳐서 생긴 문제 아닐까요?

**Comment by hb3810** [comment]
> 각각 쓰시더라도 `sample`이 겹쳐서 생긴 문제 아닐까요?

그렇다기에는 부메랑과 직선수리검은 적용이 됩니다

**Comment by realteusu** [comment]
일단 제가 잘못 말한건 각각 쓰시면 `sample`이 겹칠 수 있습니다.

제가 테스트했을때는 아마도 띄어쓰기같습니다.
yml를 로딩했을때 `abilities` 안에 이름이 있어야하고 `ability`가 있어야 하는데
```yml
abilities:
sample:
ability: com.github.noonmaru.flying-sword

abilities:
sample:
ability: com.github.noonmaru.magic-arrow

abilities:
sample:
ability: com.github.noonmaru.boomerang

abilities:
sample:
ability: com.github.noonmaru.straight-shuriken
```
이렇게 작성하셨을 경우 `abilities`랑 이름이랑 `ability`를 따로 보는것 같습니다.

```yml
abilities:
  sample:
    ability: com.github.noonmaru.flying-sword

abilities:
  sample:
    ability: com.github.noonmaru.magic-arrow

abilities:
  sample:
    ability: com.github.noonmaru.boomerang

abilities:
  sample:
    ability: com.github.noonmaru.straight-shuriken
```
이렇게 작성하셔야지 제대로 로딩이 되는것 같습니다.

**Comment by hb3810** [comment]
> 일단 제가 잘못 말한건 각각 쓰시면 `sample`이 겹칠 수 있습니다.
> 
> 제가 테스트했을때는 아마도 들여쓰기같습니다.
> yml를 로딩했을때 `abilities` 안에 이름이 있어야하고 `ability`가 있어야 하는데
> 
> ```yaml
> abilities:
> sample:
> ability: com.github.noonmaru.flying-sword
> 
> abilities:
> sample:
> ability: com.github.noonmaru.magic-arrow
> 
> abilities:
> sample:
> ability: com.github.noonmaru.boomerang
> 
> abilities:
> sample:
> ability: com.github.noonmaru.straight-shuriken
> ```
> 
> 이렇게 작성하셨을 경우 `abilities`랑 이름이랑 `ability`를 따로 보는것 같습니다.
> 
> ```yaml
> abilities:
>   sample:
>     ability: com.github.noonmaru.flying-sword
> 
> abilities:
>   sample:
>     ability: com.github.noonmaru.magic-arrow
> 
> abilities:
>   sample:
>     ability: com.github.noonmaru.boomerang
> 
> abilities:
>   sample:
>     ability: com.github.noonmaru.straight-shuriken
> ```
> 
> 이렇게 작성하셔야지 제대로 로딩이 되는것 같습니다. 이렇게 들여쓰기하셨나요?

원래 그렇게 뛰어쓰기 해놓은 상태입니다

**Comment by realteusu** [comment]
다른것도 다 하셨나요?

**Comment by hb3810** [comment]
> 다른것도 다 하셨나요?
> 
> 혹시 yml 파일 안에 `abilities`와 `sample`이 없고 `ability`밖에 없으시다면 들여쓰기 안하신겁니다

무슨 말씀이신지 잘 이해사 되지 않습니다.

**Comment by realteusu** [comment]
잘못 입력하셨다면 인식이 되지 않아 이렇게 됩니다:
```yml
ability: com.github.noonmaru.flying-sword
display-name: a
health-bonus: 0.0
health-regen-per-tick: 0.0
mana: 0.0
mana-regen-per-tick: 0.0
mana-color: BLUE
description: []
abilities: {}
```

하지만 인식이 되면:
abilities:
  sample:
    ability: com.github.noonmaru.boomerang
    common:
      display-name: 부메랑
      type: ACTIVE
      cooldown-ticks: 2
      interruptible: false
      damage:
        type: RANGED
        stats:
          ATK: 2.0
      wand:
        v: 2580
        type: GOLD_INGOT
      supply-items: []
      description:
      - 지정한 방향으로 부메랑을 빠르게 발사합니다.
      - 발사된 부메랑은 부딪힌 적에게 피해를 입히고
      - 천천히 돌아옵니다.
      - 부메랑을 회수시 다시 사용 할 수 있습니다.
    boomerang:
      boomerang-items:
      - ==: org.bukkit.inventory.ItemStack
        v: 2580
        type: RED_WOOL
      - ==: org.bukkit.inventory.ItemStack
        v: 2580
        type: YELLOW_WOOL
      - ==: org.bukkit.inventory.ItemStack
        v: 2580
        type: GREEN_WOOL
      - ==: org.bukkit.inventory.ItemStack
        v: 2580
        type: BLUE_WOOL
      - ==: org.bukkit.inventory.ItemStack
        v: 2580
        type: PURPLE_WOOL
      projectile-launch-speed: 7.0
      projectile-ticks: 200
      projectile-returning-ticks: 8
      projectile-returning-speed: 0.4
      knockback: 0.75
      ray-size: 0.3
display-name: d
health-bonus: 0.0
health-regen-per-tick: 0.0
mana: 0.0
mana-regen-per-tick: 0.0
mana-color: BLUE
description: []
```
이런식으로 파일이 변경됩니다.

**Comment by hb3810** [comment]
> 잘못 입력하셨다면 인식이 되지 않아 이렇게 됩니다:
> 
> ```yaml
> ability: com.github.noonmaru.flying-sword
> display-name: a
> health-bonus: 0.0
> health-regen-per-tick: 0.0
> mana: 0.0
> mana-regen-per-tick: 0.0
> mana-color: BLUE
> description: []
> abilities: {}
> ```
> 
> 이런 경우는 작동이 되지 않습니다.
> 하지만 인식이 되면:
> 
> ```yaml
> abilities:
>   sample:
>     ability: com.github.noonmaru.flying-sword
>     common:
>       display-name: 비도
>       type: ACTIVE
>       cooldown-ticks: 10
>       cost: 10.0
>       interruptible: false
>       range: 32.0
>       supply-items: []
>       description:
>       - 검을 우클릭하여 비검을 소환합니다.
>       - 최대 ${flying-sword.max-summon-count}개 소환 가능하며
>       - 좌클릭으로 발사 할 수 있습니다.
>       - 적에게 적중시 다음 피해를 입힙니다.
>       - '나무: <wooden><wooden-damage>'
>       - '돌: <stone><stone-damage>'
>       - '철: <iron><iron-damage>'
>       - '금: <golden><golden-damage>'
>       - '다이아몬드: <diamond><diamond-damage>'
>       - '네더라이트: <netherite><netherite-damage>'
>       - 날카로움 인챈트당 ${flying-sword.bonus-damage-by-sharpness * 100}%의 추가 피해를 입힙니다.
>     flying-sword:
>       projectile-ready-ticks: 8
>       summon-ticks: 20
>       projectile-ticks: 40
>       projectile-speed: 4.0
>       max-summon-count: 5
>       ray-size: 1.0
>       wooden:
>         type: RANGED
>         stats:
>           ATK: 1.0
>       stone:
>         type: RANGED
>         stats:
>           ATK: 1.5
>       iron:
>         type: RANGED
>         stats:
>           ATK: 2.0
>       golden:
>         type: RANGED
>         stats:
>           ATK: 2.5
>       diamond:
>         type: RANGED
>         stats:
>           ATK: 3.0
>       netherite:
>         type: RANGED
>         stats:
>           ATK: 3.5
>       bonus-damage-by-sharpness: 0.1
> display-name: a
> health-bonus: 0.0
> health-regen-per-tick: 0.0
> mana: 0.0
> mana-regen-per-tick: 0.0
> mana-color: BLUE
> description: []
> ```
> 
> 이런식으로 파일이 변경되면서, 작동됩니다.

원래 위처럼 떴었는데 이제 그마저도 안뜹니다

**Comment by yoomath2018** [comment]
공식 위키에선 한 개에 abilities:에 모든 능력을 다 담아야 한다고 나옵니다.
예시:
```
abilities:
  sample:
    ability: com.github.noonmaru.flying-sword
  secondsample:
    ability: com.github.noonmaru.magic-arrow
  thirdsample:
    ability: com.github.noonmaru.boomerang
  fourthsample:
    ability: com.github.noonmaru.straight-shuriken
```

**Comment by hb3810** [comment]
> 공식 위키에선 한 개에 abilities:에 모든 능력을 다 담아야 한다고 나옵니다.
> 예시:
> 
> ```
> abilities:
>   sample:
>     ability: com.github.noonmaru.flying-sword
>   secondsample:
>     ability: com.github.noonmaru.magic-arrow
>   thirdsample:
>     ability: com.github.noonmaru.boomerang
>   fourthsample:
>     ability: com.github.noonmaru.straight-shuriken
> ```

아 그런건가요? 감사합니다

**Comment by hb3810** [comment]
> 공식 위키에선 한 개에 abilities:에 모든 능력을 다 담아야 한다고 나옵니다.
> 예시:
> 
> ```
> abilities:
>   sample:
>     ability: com.github.noonmaru.flying-sword
>   secondsample:
>     ability: com.github.noonmaru.magic-arrow
>   thirdsample:
>     ability: com.github.noonmaru.boomerang
>   fourthsample:
>     ability: com.github.noonmaru.straight-shuriken
> ```

적용이 되지 않았습니다

**Comment by realteusu** [comment]
yml 파일이 어떻게 됐는지 첨부해주실수 있나요?

**Comment by hb3810** [comment]
> yml 파일이 어떻게 됐는지 첨부해주실수 있나요?

변경되지 않았습니다

**Comment by realteusu** [comment]
제 말은 yml이 어떻게 생겼는지 볼려고 첨부해달라는겁니다.
변경되지 않았다는게
```yml
abilities:
  sample:
    ability: com.github.noonmaru.flying-sword
  secondsample:
    ability: com.github.noonmaru.magic-arrow
  thirdsample:
    ability: com.github.noonmaru.boomerang
  fourthsample:
    ability: com.github.noonmaru.straight-shuriken
```
이상태로 계속 있었던 것인가요?

**Comment by hb3810** [comment]
> 제 말은 yml이 어떻게 생겼는지 볼려고 첨부해달라는겁니다.
> 변경되지 않았다는게
> 
> ```yaml
> abilities:
>   sample:
>     ability: com.github.noonmaru.flying-sword
>   secondsample:
>     ability: com.github.noonmaru.magic-arrow
>   thirdsample:
>     ability: com.github.noonmaru.boomerang
>   fourthsample:
>     ability: com.github.noonmaru.straight-shuriken
> ```
> 
> 이상태로 계속 있었던 것인가요?

네 그렇습니다

**Comment by realteusu** [comment]
그 yml 파일이 어디에 위치되있는지 알 수 있을까요?

**Comment by hb3810** [comment]
> 그 yml 파일이 어디에 위치되있는지 알 수 있을까요?

서버 폴더 안 plugins폴더 안 Psychis 안 psychis에 있습니다

**Comment by realteusu** [comment]
모든 능력들이 최신상태인가요?

**Comment by hb3810** [comment]
> 모든 능력들이 최신상태인가요?

네 그렇습니다

**Comment by realteusu** [comment]
> > 제 말은 yml이 어떻게 생겼는지 볼려고 첨부해달라는겁니다.
> > 변경되지 않았다는게
> > ```yaml
> > abilities:
> >   sample:
> >     ability: com.github.noonmaru.flying-sword
> >   secondsample:
> >     ability: com.github.noonmaru.magic-arrow
> >   thirdsample:
> >     ability: com.github.noonmaru.boomerang
> >   fourthsample:
> >     ability: com.github.noonmaru.straight-shuriken
> > ```
> > 
> > 
> > 이상태로 계속 있었던 것인가요?
> 
> 네 그렇습니다

이상태로 그대로 있었다는 것은 파일 인식을 못한거 같은데요?

**Comment by hb3810** [comment]
> > > 제 말은 yml이 어떻게 생겼는지 볼려고 첨부해달라는겁니다.
> > > 변경되지 않았다는게
> > > ```yaml
> > > abilities:
> > >   sample:
> > >     ability: com.github.noonmaru.flying-sword
> > >   secondsample:
> > >     ability: com.github.noonmaru.magic-arrow
> > >   thirdsample:
> > >     ability: com.github.noonmaru.boomerang
> > >   fourthsample:
> > >     ability: com.github.noonmaru.straight-shuriken
> > > ```
> > > 
> > > 
> > > 이상태로 계속 있었던 것인가요?
> > 
> > 
> > 네 그렇습니다
> 
> 이상태로 그대로 있었다는 것은 파일 인식을 못한거 같은데요?

그렇다면 어떻게 해결해야 하나요?

**Comment by realteusu** [comment]
콘솔에 뜬 에러같은게 없었나요?

**Comment by hb3810** [comment]
> 콘솔에 뜬 에러같은게 없었나요?

위에 첨부해 두었습니다.

**Comment by realteusu** [comment]
`Failed to render template token ${magic-archer.arrow-delay-ticks / 20.0}` 라고 뜨는데 딜레이 틱을 따로 설정하셨나요?

**Comment by hb3810** [comment]
> `Failed to render template token ${magic-archer.arrow-delay-ticks / 20.0}` 라고 뜨는데 딜레이 틱을 따로 설정하셨나요?

아니요 따로 설정하지는 않았습니다

**Comment by realteusu** [comment]
그러면 `psychics`를 최신버전인 [0.9.3](https://github.com/noonmaru/psychics/releases/download/0.9.3/Psychics.jar)으로 돌려보시고 [abilities.zip](https://github.com/noonmaru/psychics/releases/download/0.9.3/abilities.zip)도 다시 받아서 사용해보시겠어요?

**Comment by hb3810** [comment]
> 그러면 `psychics`를 최신버전인 [0.9.3](https://github.com/noonmaru/psychics/releases/download/0.9.3/Psychics.jar)으로 돌려보시고 [abilities.zip](https://github.com/noonmaru/psychics/releases/download/0.9.3/abilities.zip)도 다시 받아서 사용해보시겠어요?

그렇게 한 상태입니다

**Comment by realteusu** [comment]
그리고 새로 돌렸을 때 똑같은 에러가 나왔나요?

**Comment by hb3810** [comment]
> 그리고 새로 돌렸을 때 똑같은 에러가 나왔나요?

네 그렇습니다

**Comment by ghost** [comment]
@hb3810 Java 버전을 알려주실수 있나요?
Example : JDK or JRE 1.8.0_271

**Comment by realteusu** [comment]
Same issue found #91.

일단 `yaml` 파일은 이상 없어 보입니다.

로그를 자세히 보시면
`[19:09:11 WARN]: Caused by: java.lang.IllegalArgumentException: Failed to evaluate 0.1 * 100`
이라고 뜨는데 실제로 [Tap](https://github.com/noonmaru/tap)에서 `Template`를 parse하는데 `javax.script`를 이용하여 `JavaScript`라는 언어로 `eval`을 통해서 계산합니다.

여기서 문제가 될 수 있는건
 - Environment 세팅
 - Java 문제
 - [Tap](https://github.com/noonmaru/tap) 코드 문제

이렇게 추려낼 수 있겠네요.

**Comment by hb3810** [comment]
> @hb3810 Java 버전을 알려주실수 있나요?
> Example : JDK or JRE 1.8.0_271

JAVA 15입니다

**Comment by hb3810** [comment]
> Same issue found #91.
> 
> 일단 `yaml` 파일은 이상 없어 보입니다.
> 
> 로그를 자세히 보시면
> `[19:09:11 WARN]: Caused by: java.lang.IllegalArgumentException: Failed to evaluate 0.1 * 100`
> 이라고 뜨는데 실제로 [Tap](https://github.com/noonmaru/tap)에서 `Template`를 parse하는데 `javax.script`를 이용하여 `JavaScript`라는 언어로 `eval`을 통해서 계산합니다.
> 
> 여기서 문제가 될 수 있는건
> 
> * Environment 세팅
> * Java 문제
> * [Tap](https://github.com/noonmaru/tap) 코드 문제
> 
> 이렇게 추려낼 수 있겠네요.

어떻게 하면 해결할 수 있는지 알려주실 수 있나요?

**Comment by SPMKIRON** [comment]
abilities:
  sample:
    ability: com.github.noonmaru.flying-sword
  secondsample:
    ability: com.github.noonmaru.magic-arrow
  thirdsample:
    ability: com.github.noonmaru.boomerang
  fourthsample:
    ability: com.github.noonmaru.straight-shuriken

secondsample에 -를 안붙였네요.
second-sample 이렇게 해야 합니다.
그리고 0.9.3버전 썼을때 저는 thirdsample, fourthsample 안하고

abilities:
  sample:
    ability: com.github.noonmaru.boomerang
  second-sample:
    ability: com.github.noonmaru.magic-arrow

이렇게 했는데 맞는지 모르겠네요.

**Comment by SPMKIRON** [comment]
혹시 .yml 작성한거 그대로 복붙해서 보여주시는거 가능 하십니까?

**Comment by hb3810** [comment]
> 혹시 .yml 작성한거 그대로 복붙해서 보여주시는거 가능 하십니까?


abilities:
  sample:
    ability: com.github.noonmaru.flying-sword


abilities:
  sample:
    ability: com.github.noonmaru.magic-arrow

입니다

**Comment by SPMKIRON** [comment]
abilities:
  sample:
    ability: com.github.noonmaru.boomerang
  second-sample:
    ability: com.github.noonmaru.magic-arrow

이런식으로 해야 되고요.second-sample이라고 적어야 됩니다.

**Comment by SPMKIRON** [comment]
아 그리고 이거 위키에 작성하기를 참고해 주시면 되겠습니다.

**Comment by hb3810** [comment]
> abilities:
> sample:
> ability: com.github.noonmaru.boomerang
> second-sample:
> ability: com.github.noonmaru.magic-arrow
> 
> 이런식으로 해야 되고요.second-sample이라고 적어야 됩니다.

저렇게 썼을 때 나머지 두개는 정상적으로 작동하였습니다

> abilities:
> sample:
> ability: com.github.noonmaru.boomerang
> second-sample:
> ability: com.github.noonmaru.magic-arrow
> 
> 이런식으로 해야 되고요.second-sample이라고 적어야 됩니다.

이렇게 해보았는데 적용이 되었다고 떠서 해보니 제대로 적용이 되어 있지 않았습니다

**Comment by realteusu** [comment]
> > @hb3810 Java 버전을 알려주실수 있나요?
> > Example : JDK or JRE 1.8.0_271
> 
> JAVA 15입니다

혹시 JRE 8로 바꿔보시겠어요?
15버전이 문제가 있는 걸 수도 있습니다.

**Comment by ghost** [comment]
JDK 문제인거 같네요
저도 이런 오류가 있었는데 JDK 11로 바꾸니 적용이 잘 되네요
그 전 버전도 될꺼 같고요

**Comment by ghost** [comment]
Tap, Kotlin 사용시 JRE 혹은 JDK를 8 혹은 11로 하시는걸 권장합니다.

**Comment by hb3810** [comment]
도와주신 모든 분들 감사합니다. 해결되었습니다. 질문은 닫겠습니다. 감사합니다.
