### ISSUE TITLE
모든 플러그인을 최신 버전으로 올렸더니 블럭 부메랑이랑 직선수리검 능력이 작동하지 않네요

### ISSUE THREAD

**Issue by ohgi07** [noonmaru/psychics#68]
모든 의존 플러그인을 최신 버전으로 올렸습니다 그런데 직선수리검은 마나만 감소하고 날아가지 않고 블럭 부메랑은 아무리 클릭해도 날아가지 않는 문제가 발생 했습니다
어떻게 해결해야 할까요?

**Comment by dinooo5252** [comment]
능력들의 최신버전을 적용해주세요.

**Comment by ohgi07** [comment]
@dinooo5252 아 그걸 깜빡했네요
감사합니다
