### ISSUE TITLE
이상한 것 

### ISSUE THREAD

**Issue by jini5012** [noonmaru/psychics#7]
제가 psychics를 빌드를 하고 빌드가 된 파일이 없어서 이렇게 말을 해드립니다.(이상하다 원래 build\libs 안에 있었는데 그 build가 아예 없던데.......)

**Comment by pllume** [comment]
기억은 잘 안나지만 psychics-common\build\libs 에 있던걸로 압니다.

**Comment by jini5012** [comment]
그렇네요
