### ISSUE TITLE
여기 파일을 어떻게 구하나요..?

### ISSUE THREAD

**Issue by UniKue3118** [noonmaru/psychics#72]
C:\Users\(사용자 이름)\.gradle\caches\modules-2\files-2.1\com.github.noonmaru\psychics
여기에 0.9.2 최신 파일이 있어야 할것 같은데
https://github.com/noonmaru/psychics-abilities
여기 프로젝트 가져와 쓰면 0.8.0 버전이 계속 불러와지는 것 같습니다.. 그것 땜에 직루토 코드 그대로 붙여넣어도 제대로 적용이 안되는데 어떻게 해결할 방법이 없나요오..?
![제목 없음](https://user-images.githubusercontent.com/72347184/96594415-8883f880-1325-11eb-91b1-a13f93aee37b.png)

**Comment by jini5012** [comment]
C:\Users\사용자 이름\github files\psychics-abilities-master\abilities\build.gradle.kts에서 compileOnly에 써있는 psychics버전을 0.9.2로 하면 될껍니다.

**Comment by jini5012** [comment]
저는 전에 다운로드 받아서 0.7.1로 되있네요

**Comment by UniKue3118** [comment]
아.. 살짝 이해하질 못해서 약간 차질이 있었는데 어찌됬든 해결되었습니다..
(\github files\psychics-abilities-master\)여기 부분에 자신의 프로젝트 폴더를 적는거였군요
감사합니다!

**Comment by jini5012** [comment]
아 죄송합니다
