### ISSUE TITLE
wiki를 따라해서 .yml도 쓰고 구성을 했는데 아머스탠드의 형채가 안보여요.

### ISSUE THREAD

**Issue by JAYDY0102** [noonmaru/psychics#75]
abilities:
  sample:
    ability: com.github.noonmaru.boomerang
    common:
      display-name: 부메랑
      type: ACTIVE
      cooldown-ticks: 2
      interruptible: false
      damage:
        type: RANGED
        stats:
          ATK: 2.0
      wand:
        v: 2580
        type: GOLD_INGOT
      supply-items: &id001 []
      description:
      - 지정한 방향으로 부메랑을 빠르게 발사합니다.
      - 발사된 부메랑은 부딪힌 적에게 피해를 입히고
      - 천천히 돌아옵니다.
      - 부메랑을 회수시 다시 사용 할 수 있습니다.
    boomerang:
      boomerang-items:
      - ==: org.bukkit.inventory.ItemStack
        v: 2580
        type: RED_WOOL
      - ==: org.bukkit.inventory.ItemStack
        v: 2580
        type: YELLOW_WOOL
      - ==: org.bukkit.inventory.ItemStack
        v: 2580
        type: GREEN_WOOL
      - ==: org.bukkit.inventory.ItemStack
        v: 2580
        type: BLUE_WOOL
      - ==: org.bukkit.inventory.ItemStack
        v: 2580
        type: PURPLE_WOOL
      projectile-launch-speed: 7.0
      projectile-ticks: 200
      projectile-returning-ticks: 8
      projectile-returning-speed: 0.4
      knockback: 0.75
      ray-size: 0.3
display-name: boomerang
health-bonus: 0.0
health-regen-per-tick: 0.0
mana: 100
mana-regen-per-tick: 1.0
mana-color: BLUE
description: []
로 썼는데 블록이 주변을 돌지 않고 보이지 않아요

**Comment by realteusu** [comment]
```yml
abilities:
  sample:
    ability: com.github.noonmaru.boomerang
```
만 작성해주시고 서버를 켜주세요. 다른 값들은 자동으로 추가되고 그 값들을 바꿔주시면 됩니다.

**Comment by devil0414** [comment]
Protocolib, kotlin 등의 플러그인도 사용하셨나요?

**Comment by JAYDY0102** [comment]
네

**Comment by JAYDY0102** [comment]
> ```yaml
> abilities:
>   sample:
>     ability: com.github.noonmaru.boomerang
> ```
> 
> 만 작성해주시고 서버를 켜주세요. 다른 값들은 자동으로 추가되고 그 값들을 바꿔주시면 됩니다.
> 
> * 마나가 필요한 능력은 마나와 마나 틱당 충전 기본 값이 0입니다. 그 값들을 바꿔주셔야지 마나와 마나 충전이 작동합니다.

그것만 적고 지금 .yml 파일에 있는것을 쓴겁니다.

**Comment by realteusu** [comment]
콘솔에 에러같은건 안뜨셨나요

**Comment by JAYDY0102** [comment]
에러는 없는데요.

**Comment by JAYDY0102** [comment]
서버 퍼미션 .yml이 비어있데요.

**Comment by realteusu** [comment]
로그좀 보여주시겠어요?

**Comment by JAYDY0102** [comment]
한번 서버를 재시작 해볼게요

**Comment by JAYDY0102** [comment]
어

**Comment by JAYDY0102** [comment]
됐다

**Comment by realteusu** [comment]
정상적으로 작동됐으면 이슈 닫아주세요~
