### ISSUE TITLE
Docker 사용 방법에 대한 문의

### ISSUE THREAD

**Issue by Apple6050** [noonmaru/psychics#77]
현재 컴퓨터에 Docker Desktop를 설치하고 Hyper-V까지 켜놓은 상태이고
itzg/miencraft-server 컨테이너 이미지까지 설치해놓았습니다.
하지만 사용을 어떻게 하는지 모르겠습니다.
Tap에 있는 Issue를 봐서는 Tap README에 적혀있는데로 해보니 오류가 떴습니다
쟤 컴퓨터 문제인지 아니면 Docker 문제인지는 모르겠는데
noonmaru님이 직접 방법을 가르쳐주시면 사용이 가능할려나 싶어서 이슈를 만듭니다.

**Comment by Apple6050** [comment]
@noonmaru

**Comment by noonmaru** [comment]
`docker-compose up --build -d`

명령을 사용하시면 됩니다.

해당 오류는 저도 뭔지 잘 모르겠습니다. ㅜㅜ

도커 설치중 오류인지 wsl오류인지 모르겠네요

재설치 해보시는걸..

**Comment by Apple6050** [comment]
해결될시 이슈 닫겠습니다.@noonmaru

**Comment by Apple6050** [comment]
![image](https://user-images.githubusercontent.com/65204013/97647800-7bd67180-1a96-11eb-86ec-86ca01d846f4.png)
이 프로그램이 맞나요?

**Comment by Apple6050** [comment]
@noonmaru

**Comment by Apple6050** [comment]
[I Used This Download Link](https://www.docker.com/products/docker-desktop)

**Comment by Apple6050** [comment]
재설치후 문제 해결했습니다! 감사합니다! @noonmaru 이슈 닫겠습니다.!
