### ISSUE TITLE
paper 서버 1.16.4

### ISSUE THREAD

**Issue by hajun0827** [noonmaru/psychics#78]
1.16.4로 업데이트 후 일부 능력이 작동하지 않습니다.

적용은 되나 작동하지 않는 코드도 있고 아예 적용되지 않는 코드도 있습니다.
업데이트 이전에는 잘 작동했던 코드입니다.

혹시 psychics 플러그인이 업데이트가 필요한가요?

아니면 제 코드 문제니 저 혼자 해결해보겠습니다...

**Comment by UniKue3118** [comment]
코드가 1.16.3 버전을 기준으로 작성하여 1.16.4 버전에서는 작동이 안될수도 있습니다. 저도 오류가 있었는데 버전이 맞지 않아 발생하는 오류 같습니다. 플러그인이 업데이트 될때까지 기다려봐야겠죠..?
