### ISSUE TITLE
직선환

### ISSUE THREAD

**Issue by eric236** [noonmaru/psychics#80]
각별님의 직선수리검을 직선환으로 바꾸어 보려고 하는데 어떻게 할까요? 제가 코딩을 잘못해서 알려주시면 감사하겠습니다.

**Comment by eric236** [comment]
임시로 만든 psychics는 감지가 되는데 어빌리티가 없습니다

**Comment by zlfn** [comment]
이곳은 프로그램 실행/빌드시 오류, 문제점들을 보고하는 곳이지 코딩하는 법을 가르쳐 주는 곳이 아닙니다. 플러그인을 코딩하는 법을 배우고 싶으시다면 https://www.spigotmc.org/wiki/spigot-plugin-development/ 같은 공식 영문 튜토리얼이나 블로그같은 곳에 사람들이 올려놓은 한글튜토리얼을 참고해주세요.
