### ISSUE TITLE
빌드를 어떻게 해야하나요?

### ISSUE THREAD

**Issue by HKjay** [noonmaru/psychics#9]
빌드를 어떻게 해야하나요?

**Comment by pllume** [comment]
1. psychics-0.6.0.zip 을 다운받고 그 안에 있는 psychics-0.6.0 파일을 꺼집어내줍니다
2. 명령 프롬포트를 실행하신 후 cd (psychics-0.6.0 파일 경로) 를 쳐줍니다
3. 그리고 gradlew.bat tasks 을 칩니다
4. 그리고 거기 tasks 중에서 ShadowJar를 선택합니다
5. psychics-0.6.0\psychics-common\build\libs 안에 Psychics.jar가 생성되었을 겁니다

자 이제 이 플러그인을 적용시키기 위해서는 다음 플러그인이 필요합니다.
1. AutoReloader 1.0.1
2. InvFX 1.3.0
3. Tap 3.1.7
4. Kotlin-plugin 1.4.10
모두 각별님의 Repositories 안에 있으니 잘 찾아보세요

모두 다운 받으셨다면 Psychics.jar 와 같이 다 plugins 폴더에 넣어주세요
